/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkRemoveJobRequestDto,
  BulkRemoveJobRequestEntity,
  ExceptionResponseEntity,
  ExecuteBulkRemoveJobRequestBodyDto,
} from '../models/index';
import {
    BulkRemoveJobRequestDtoFromJSON,
    BulkRemoveJobRequestDtoToJSON,
    BulkRemoveJobRequestEntityFromJSON,
    BulkRemoveJobRequestEntityToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    ExecuteBulkRemoveJobRequestBodyDtoFromJSON,
    ExecuteBulkRemoveJobRequestBodyDtoToJSON,
} from '../models/index';

export interface ProcessBulkRemoveRequest {
    executeBulkRemoveJobRequestBodyDto: ExecuteBulkRemoveJobRequestBodyDto;
}

export interface ScheduleBulkRemoveRequest {
    bulkRemoveJobRequestDto: BulkRemoveJobRequestDto;
}

/**
 * BulkRemoveApi - interface
 * 
 * @export
 * @interface BulkRemoveApiInterface
 */
export interface BulkRemoveApiInterface {
    /**
     * 
     * @summary Processes bulk remove tasks
     * @param {ExecuteBulkRemoveJobRequestBodyDto} executeBulkRemoveJobRequestBodyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkRemoveApiInterface
     */
    processBulkRemoveRaw(requestParameters: ProcessBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Processes bulk remove tasks
     */
    processBulkRemove(requestParameters: ProcessBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Schedules removal of multiple resources
     * @param {BulkRemoveJobRequestDto} bulkRemoveJobRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkRemoveApiInterface
     */
    scheduleBulkRemoveRaw(requestParameters: ScheduleBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkRemoveJobRequestEntity>>;

    /**
     * Schedules removal of multiple resources
     */
    scheduleBulkRemove(requestParameters: ScheduleBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkRemoveJobRequestEntity>;

}

/**
 * 
 */
export class BulkRemoveApi extends runtime.BaseAPI implements BulkRemoveApiInterface {

    /**
     * Processes bulk remove tasks
     */
    async processBulkRemoveRaw(requestParameters: ProcessBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['executeBulkRemoveJobRequestBodyDto'] == null) {
            throw new runtime.RequiredError(
                'executeBulkRemoveJobRequestBodyDto',
                'Required parameter "executeBulkRemoveJobRequestBodyDto" was null or undefined when calling processBulkRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/queues/bulk-remove`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecuteBulkRemoveJobRequestBodyDtoToJSON(requestParameters['executeBulkRemoveJobRequestBodyDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Processes bulk remove tasks
     */
    async processBulkRemove(requestParameters: ProcessBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.processBulkRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Schedules removal of multiple resources
     */
    async scheduleBulkRemoveRaw(requestParameters: ScheduleBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkRemoveJobRequestEntity>> {
        if (requestParameters['bulkRemoveJobRequestDto'] == null) {
            throw new runtime.RequiredError(
                'bulkRemoveJobRequestDto',
                'Required parameter "bulkRemoveJobRequestDto" was null or undefined when calling scheduleBulkRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/external/bulk/remove`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkRemoveJobRequestDtoToJSON(requestParameters['bulkRemoveJobRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkRemoveJobRequestEntityFromJSON(jsonValue));
    }

    /**
     * Schedules removal of multiple resources
     */
    async scheduleBulkRemove(requestParameters: ScheduleBulkRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkRemoveJobRequestEntity> {
        const response = await this.scheduleBulkRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
