/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExceptionResponseEntity,
  ProcessExportResourceJobRequestBodyDto,
} from '../models/index';
import {
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    ProcessExportResourceJobRequestBodyDtoFromJSON,
    ProcessExportResourceJobRequestBodyDtoToJSON,
} from '../models/index';

export interface ExecuteExportResourceRequest {
    processExportResourceJobRequestBodyDto: ProcessExportResourceJobRequestBodyDto;
}

/**
 * ExportResourcesApi - interface
 * 
 * @export
 * @interface ExportResourcesApiInterface
 */
export interface ExportResourcesApiInterface {
    /**
     * 
     * @summary Executa a exportação de um recurso.
     * @param {ProcessExportResourceJobRequestBodyDto} processExportResourceJobRequestBodyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportResourcesApiInterface
     */
    executeExportResourceRaw(requestParameters: ExecuteExportResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Executa a exportação de um recurso.
     */
    executeExportResource(requestParameters: ExecuteExportResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ExportResourcesApi extends runtime.BaseAPI implements ExportResourcesApiInterface {

    /**
     * Executa a exportação de um recurso.
     */
    async executeExportResourceRaw(requestParameters: ExecuteExportResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['processExportResourceJobRequestBodyDto'] == null) {
            throw new runtime.RequiredError(
                'processExportResourceJobRequestBodyDto',
                'Required parameter "processExportResourceJobRequestBodyDto" was null or undefined when calling executeExportResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/internal/queues/export-resources`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProcessExportResourceJobRequestBodyDtoToJSON(requestParameters['processExportResourceJobRequestBodyDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Executa a exportação de um recurso.
     */
    async executeExportResource(requestParameters: ExecuteExportResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.executeExportResourceRaw(requestParameters, initOverrides);
    }

}
