/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FinancialRecordRadarItemAutoExecuteSettingEntity,
  UpdateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto,
} from '../models/index';
import {
    FinancialRecordRadarItemAutoExecuteSettingEntityFromJSON,
    FinancialRecordRadarItemAutoExecuteSettingEntityToJSON,
    UpdateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDtoFromJSON,
    UpdateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDtoToJSON,
} from '../models/index';

export interface UpdateFinancialRecordRadarItemAutoExecuteSettingsRequest {
    updateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto: UpdateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto;
}

/**
 * FinancialRecordRadarItemAutoExecuteApi - interface
 * 
 * @export
 * @interface FinancialRecordRadarItemAutoExecuteApiInterface
 */
export interface FinancialRecordRadarItemAutoExecuteApiInterface {
    /**
     * Retorna as configurações de auto-execute do radar para a organização do usuário.
     * @summary Obter configurações de auto-execute
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FinancialRecordRadarItemAutoExecuteApiInterface
     */
    getFinancialRecordRadarItemAutoExecuteSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordRadarItemAutoExecuteSettingEntity>>;

    /**
     * Retorna as configurações de auto-execute do radar para a organização do usuário.
     * Obter configurações de auto-execute
     */
    getFinancialRecordRadarItemAutoExecuteSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordRadarItemAutoExecuteSettingEntity>;

    /**
     * Atualiza as configurações de auto-execute do radar para a organização do usuário.
     * @summary Atualizar configurações de auto-execute
     * @param {UpdateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto} updateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FinancialRecordRadarItemAutoExecuteApiInterface
     */
    updateFinancialRecordRadarItemAutoExecuteSettingsRaw(requestParameters: UpdateFinancialRecordRadarItemAutoExecuteSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordRadarItemAutoExecuteSettingEntity>>;

    /**
     * Atualiza as configurações de auto-execute do radar para a organização do usuário.
     * Atualizar configurações de auto-execute
     */
    updateFinancialRecordRadarItemAutoExecuteSettings(requestParameters: UpdateFinancialRecordRadarItemAutoExecuteSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordRadarItemAutoExecuteSettingEntity>;

}

/**
 * 
 */
export class FinancialRecordRadarItemAutoExecuteApi extends runtime.BaseAPI implements FinancialRecordRadarItemAutoExecuteApiInterface {

    /**
     * Retorna as configurações de auto-execute do radar para a organização do usuário.
     * Obter configurações de auto-execute
     */
    async getFinancialRecordRadarItemAutoExecuteSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordRadarItemAutoExecuteSettingEntity>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/financial-records/radar/items/auto-execute/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinancialRecordRadarItemAutoExecuteSettingEntityFromJSON(jsonValue));
    }

    /**
     * Retorna as configurações de auto-execute do radar para a organização do usuário.
     * Obter configurações de auto-execute
     */
    async getFinancialRecordRadarItemAutoExecuteSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordRadarItemAutoExecuteSettingEntity> {
        const response = await this.getFinancialRecordRadarItemAutoExecuteSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Atualiza as configurações de auto-execute do radar para a organização do usuário.
     * Atualizar configurações de auto-execute
     */
    async updateFinancialRecordRadarItemAutoExecuteSettingsRaw(requestParameters: UpdateFinancialRecordRadarItemAutoExecuteSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialRecordRadarItemAutoExecuteSettingEntity>> {
        if (requestParameters['updateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto'] == null) {
            throw new runtime.RequiredError(
                'updateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto',
                'Required parameter "updateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto" was null or undefined when calling updateFinancialRecordRadarItemAutoExecuteSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/external/financial-records/radar/items/auto-execute/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDtoToJSON(requestParameters['updateFinancialRecordRadarItemAutoExecuteSettingsRequestBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinancialRecordRadarItemAutoExecuteSettingEntityFromJSON(jsonValue));
    }

    /**
     * Atualiza as configurações de auto-execute do radar para a organização do usuário.
     * Atualizar configurações de auto-execute
     */
    async updateFinancialRecordRadarItemAutoExecuteSettings(requestParameters: UpdateFinancialRecordRadarItemAutoExecuteSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialRecordRadarItemAutoExecuteSettingEntity> {
        const response = await this.updateFinancialRecordRadarItemAutoExecuteSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
