/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExceptionResponseEntity,
  HealthResponseDto,
} from '../models/index';
import {
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    HealthResponseDtoFromJSON,
    HealthResponseDtoToJSON,
} from '../models/index';

/**
 * HealthApi - interface
 * 
 * @export
 * @interface HealthApiInterface
 */
export interface HealthApiInterface {
    /**
     * Creates request options for error without sending the request
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    errorRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Gera um erro de teste.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    errorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Gera um erro de teste.
     */
    error(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for health without sending the request
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Verifica o status do serviço.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponseDto>>;

    /**
     * Verifica o status do serviço.
     */
    health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponseDto>;

    /**
     * Creates request options for healthPost without sending the request
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthPostRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Verifica o status do serviço.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponseDto>>;

    /**
     * Verifica o status do serviço.
     */
    healthPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponseDto>;

}

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI implements HealthApiInterface {

    /**
     * Creates request options for error without sending the request
     */
    async errorRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/error`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gera um erro de teste.
     */
    async errorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.errorRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Gera um erro de teste.
     */
    async error(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.errorRaw(initOverrides);
    }

    /**
     * Creates request options for health without sending the request
     */
    async healthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verifica o status do serviço.
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponseDto>> {
        const requestOptions = await this.healthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Verifica o status do serviço.
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponseDto> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthPost without sending the request
     */
    async healthPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verifica o status do serviço.
     */
    async healthPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponseDto>> {
        const requestOptions = await this.healthPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Verifica o status do serviço.
     */
    async healthPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponseDto> {
        const response = await this.healthPostRaw(initOverrides);
        return await response.value();
    }

}
