/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateQueryRequestDto,
  ExceptionResponseEntity,
  QueryResponseDto,
} from '../models/index';
import {
    CreateQueryRequestDtoFromJSON,
    CreateQueryRequestDtoToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    QueryResponseDtoFromJSON,
    QueryResponseDtoToJSON,
} from '../models/index';

export interface CreateQueryRequest {
    createQueryRequestDto: CreateQueryRequestDto;
}

export interface FindByIdQueryRequest {
    id: string;
}

/**
 * QueriesApi - interface
 * 
 * @export
 * @interface QueriesApiInterface
 */
export interface QueriesApiInterface {
    /**
     * 
     * @summary Cria uma nova consulta.
     * @param {CreateQueryRequestDto} createQueryRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueriesApiInterface
     */
    createQueryRaw(requestParameters: CreateQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponseDto>>;

    /**
     * Cria uma nova consulta.
     */
    createQuery(requestParameters: CreateQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponseDto>;

    /**
     * 
     * @summary Busca uma consulta pelo identificador.
     * @param {string} id Identificador da consulta.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueriesApiInterface
     */
    findByIdQueryRaw(requestParameters: FindByIdQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponseDto>>;

    /**
     * Busca uma consulta pelo identificador.
     */
    findByIdQuery(requestParameters: FindByIdQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponseDto>;

}

/**
 * 
 */
export class QueriesApi extends runtime.BaseAPI implements QueriesApiInterface {

    /**
     * Cria uma nova consulta.
     */
    async createQueryRaw(requestParameters: CreateQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponseDto>> {
        if (requestParameters['createQueryRequestDto'] == null) {
            throw new runtime.RequiredError(
                'createQueryRequestDto',
                'Required parameter "createQueryRequestDto" was null or undefined when calling createQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/external/queries`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateQueryRequestDtoToJSON(requestParameters['createQueryRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseDtoFromJSON(jsonValue));
    }

    /**
     * Cria uma nova consulta.
     */
    async createQuery(requestParameters: CreateQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponseDto> {
        const response = await this.createQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Busca uma consulta pelo identificador.
     */
    async findByIdQueryRaw(requestParameters: FindByIdQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling findByIdQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/queries/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseDtoFromJSON(jsonValue));
    }

    /**
     * Busca uma consulta pelo identificador.
     */
    async findByIdQuery(requestParameters: FindByIdQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponseDto> {
        const response = await this.findByIdQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
