/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExceptionResponseEntity,
  ExportSubcategoriesDto,
} from '../models/index';
import {
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    ExportSubcategoriesDtoFromJSON,
    ExportSubcategoriesDtoToJSON,
} from '../models/index';

export interface ExportSubcategoriesRequest {
    sortOrder?: ExportSubcategoriesSortOrderEnum;
    sortBy?: ExportSubcategoriesSortByEnum;
    active?: boolean;
    categoryId?: string;
    direction?: ExportSubcategoriesDirectionEnum;
    format?: ExportSubcategoriesFormatEnum;
}

/**
 * SubcategoriesExportApi - interface
 * 
 * @export
 * @interface SubcategoriesExportApiInterface
 */
export interface SubcategoriesExportApiInterface {
    /**
     * 
     * @summary Solicita a exportação das subcategorias.
     * @param {'asc' | 'desc'} [sortOrder] Ordem de ordenação das subcategorias.
     * @param {'name' | 'createdAt' | 'index'} [sortBy] Campo para ordenar as subcategorias.
     * @param {boolean} [active] Filtra subcategorias ativas ou inativas.
     * @param {string} [categoryId] ID da categoria para filtrar subcategorias.
     * @param {'IN' | 'OUT'} [direction] Direção da subcategoria.
     * @param {'csv' | 'xlsx'} [format] Formato de exportação dos dados.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubcategoriesExportApiInterface
     */
    exportSubcategoriesRaw(requestParameters: ExportSubcategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportSubcategoriesDto>>;

    /**
     * Solicita a exportação das subcategorias.
     */
    exportSubcategories(requestParameters: ExportSubcategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportSubcategoriesDto>;

}

/**
 * 
 */
export class SubcategoriesExportApi extends runtime.BaseAPI implements SubcategoriesExportApiInterface {

    /**
     * Solicita a exportação das subcategorias.
     */
    async exportSubcategoriesRaw(requestParameters: ExportSubcategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportSubcategoriesDto>> {
        const queryParameters: any = {};

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['categoryId'] = requestParameters['categoryId'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/external/subcategories/export`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExportSubcategoriesDtoFromJSON(jsonValue));
    }

    /**
     * Solicita a exportação das subcategorias.
     */
    async exportSubcategories(requestParameters: ExportSubcategoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportSubcategoriesDto> {
        const response = await this.exportSubcategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ExportSubcategoriesSortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ExportSubcategoriesSortOrderEnum = typeof ExportSubcategoriesSortOrderEnum[keyof typeof ExportSubcategoriesSortOrderEnum];
/**
 * @export
 */
export const ExportSubcategoriesSortByEnum = {
    Name: 'name',
    CreatedAt: 'createdAt',
    Index: 'index'
} as const;
export type ExportSubcategoriesSortByEnum = typeof ExportSubcategoriesSortByEnum[keyof typeof ExportSubcategoriesSortByEnum];
/**
 * @export
 */
export const ExportSubcategoriesDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type ExportSubcategoriesDirectionEnum = typeof ExportSubcategoriesDirectionEnum[keyof typeof ExportSubcategoriesDirectionEnum];
/**
 * @export
 */
export const ExportSubcategoriesFormatEnum = {
    Csv: 'csv',
    Xlsx: 'xlsx'
} as const;
export type ExportSubcategoriesFormatEnum = typeof ExportSubcategoriesFormatEnum[keyof typeof ExportSubcategoriesFormatEnum];
