/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserEntityOrganizationChildrenInner
 */
export interface AuthUserEntityOrganizationChildrenInner {
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntityOrganizationChildrenInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntityOrganizationChildrenInner
     */
    name: string;
}

/**
 * Check if a given object implements the AuthUserEntityOrganizationChildrenInner interface.
 */
export function instanceOfAuthUserEntityOrganizationChildrenInner(value: object): value is AuthUserEntityOrganizationChildrenInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthUserEntityOrganizationChildrenInnerFromJSON(json: any): AuthUserEntityOrganizationChildrenInner {
    return AuthUserEntityOrganizationChildrenInnerFromJSONTyped(json, false);
}

export function AuthUserEntityOrganizationChildrenInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserEntityOrganizationChildrenInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function AuthUserEntityOrganizationChildrenInnerToJSON(json: any): AuthUserEntityOrganizationChildrenInner {
    return AuthUserEntityOrganizationChildrenInnerToJSONTyped(json, false);
}

export function AuthUserEntityOrganizationChildrenInnerToJSONTyped(value?: AuthUserEntityOrganizationChildrenInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

