/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthUserEntityOrganization } from './AuthUserEntityOrganization';
import {
    AuthUserEntityOrganizationFromJSON,
    AuthUserEntityOrganizationFromJSONTyped,
    AuthUserEntityOrganizationToJSON,
    AuthUserEntityOrganizationToJSONTyped,
} from './AuthUserEntityOrganization';

/**
 * 
 * @export
 * @interface AuthUserEntity
 */
export interface AuthUserEntity {
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    primaryPhoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    lastName: string;
    /**
     * 
     * @type {AuthUserEntityOrganization}
     * @memberof AuthUserEntity
     */
    organization?: AuthUserEntityOrganization | null;
}

/**
 * Check if a given object implements the AuthUserEntity interface.
 */
export function instanceOfAuthUserEntity(value: object): value is AuthUserEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    if (!('primaryPhoneNumber' in value) || value['primaryPhoneNumber'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function AuthUserEntityFromJSON(json: any): AuthUserEntity {
    return AuthUserEntityFromJSONTyped(json, false);
}

export function AuthUserEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'primaryEmail': json['primaryEmail'],
        'primaryPhoneNumber': json['primaryPhoneNumber'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'organization': json['organization'] == null ? undefined : AuthUserEntityOrganizationFromJSON(json['organization']),
    };
}

export function AuthUserEntityToJSON(json: any): AuthUserEntity {
    return AuthUserEntityToJSONTyped(json, false);
}

export function AuthUserEntityToJSONTyped(value?: AuthUserEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'primaryEmail': value['primaryEmail'],
        'primaryPhoneNumber': value['primaryPhoneNumber'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'organization': AuthUserEntityOrganizationToJSON(value['organization']),
    };
}

