/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserEntity
 */
export interface AuthUserEntity {
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    primaryPhoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    org: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    orgRole: AuthUserEntityOrgRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthUserEntity
     */
    orgType: AuthUserEntityOrgTypeEnum;
}


/**
 * @export
 */
export const AuthUserEntityOrgRoleEnum = {
    Admin: 'org:admin',
    Member: 'org:member'
} as const;
export type AuthUserEntityOrgRoleEnum = typeof AuthUserEntityOrgRoleEnum[keyof typeof AuthUserEntityOrgRoleEnum];

/**
 * @export
 */
export const AuthUserEntityOrgTypeEnum = {
    Leaf: 'LEAF',
    Group: 'GROUP'
} as const;
export type AuthUserEntityOrgTypeEnum = typeof AuthUserEntityOrgTypeEnum[keyof typeof AuthUserEntityOrgTypeEnum];


/**
 * Check if a given object implements the AuthUserEntity interface.
 */
export function instanceOfAuthUserEntity(value: object): value is AuthUserEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    if (!('primaryPhoneNumber' in value) || value['primaryPhoneNumber'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('org' in value) || value['org'] === undefined) return false;
    if (!('orgRole' in value) || value['orgRole'] === undefined) return false;
    if (!('orgType' in value) || value['orgType'] === undefined) return false;
    return true;
}

export function AuthUserEntityFromJSON(json: any): AuthUserEntity {
    return AuthUserEntityFromJSONTyped(json, false);
}

export function AuthUserEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'primaryEmail': json['primaryEmail'],
        'primaryPhoneNumber': json['primaryPhoneNumber'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'org': json['org'],
        'orgRole': json['orgRole'],
        'orgType': json['orgType'],
    };
}

export function AuthUserEntityToJSON(json: any): AuthUserEntity {
    return AuthUserEntityToJSONTyped(json, false);
}

export function AuthUserEntityToJSONTyped(value?: AuthUserEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'primaryEmail': value['primaryEmail'],
        'primaryPhoneNumber': value['primaryPhoneNumber'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'org': value['org'],
        'orgRole': value['orgRole'],
        'orgType': value['orgType'],
    };
}

