/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankTransactionsPageDtoItemsInner } from './BankTransactionsPageDtoItemsInner';
import {
    BankTransactionsPageDtoItemsInnerFromJSON,
    BankTransactionsPageDtoItemsInnerFromJSONTyped,
    BankTransactionsPageDtoItemsInnerToJSON,
    BankTransactionsPageDtoItemsInnerToJSONTyped,
} from './BankTransactionsPageDtoItemsInner';
import type { ContactsPageEntityPageInfo } from './ContactsPageEntityPageInfo';
import {
    ContactsPageEntityPageInfoFromJSON,
    ContactsPageEntityPageInfoFromJSONTyped,
    ContactsPageEntityPageInfoToJSON,
    ContactsPageEntityPageInfoToJSONTyped,
} from './ContactsPageEntityPageInfo';

/**
 * 
 * @export
 * @interface BankTransactionsPageDto
 */
export interface BankTransactionsPageDto {
    /**
     * 
     * @type {ContactsPageEntityPageInfo}
     * @memberof BankTransactionsPageDto
     */
    pageInfo: ContactsPageEntityPageInfo;
    /**
     * 
     * @type {Array<BankTransactionsPageDtoItemsInner>}
     * @memberof BankTransactionsPageDto
     */
    items: Array<BankTransactionsPageDtoItemsInner>;
}

/**
 * Check if a given object implements the BankTransactionsPageDto interface.
 */
export function instanceOfBankTransactionsPageDto(value: object): value is BankTransactionsPageDto {
    if (!('pageInfo' in value) || value['pageInfo'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BankTransactionsPageDtoFromJSON(json: any): BankTransactionsPageDto {
    return BankTransactionsPageDtoFromJSONTyped(json, false);
}

export function BankTransactionsPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransactionsPageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'pageInfo': ContactsPageEntityPageInfoFromJSON(json['pageInfo']),
        'items': ((json['items'] as Array<any>).map(BankTransactionsPageDtoItemsInnerFromJSON)),
    };
}

export function BankTransactionsPageDtoToJSON(json: any): BankTransactionsPageDto {
    return BankTransactionsPageDtoToJSONTyped(json, false);
}

export function BankTransactionsPageDtoToJSONTyped(value?: BankTransactionsPageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageInfo': ContactsPageEntityPageInfoToJSON(value['pageInfo']),
        'items': ((value['items'] as Array<any>).map(BankTransactionsPageDtoItemsInnerToJSON)),
    };
}

