/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkBankTransactionsJobRequestDto
 */
export interface BulkBankTransactionsJobRequestDto {
    /**
     * 
     * @type {string}
     * @memberof BulkBankTransactionsJobRequestDto
     */
    operation: BulkBankTransactionsJobRequestDtoOperationEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkBankTransactionsJobRequestDto
     */
    bankTransactionIds: Array<string>;
}


/**
 * @export
 */
export const BulkBankTransactionsJobRequestDtoOperationEnum = {
    Archive: 'ARCHIVE',
    Unarchive: 'UNARCHIVE',
    Unreconcile: 'UNRECONCILE',
    RequestAiSuggestion: 'REQUEST_AI_SUGGESTION',
    CreateFromAiSuggestion: 'CREATE_FROM_AI_SUGGESTION',
    ReconcileFromAiSuggestion: 'RECONCILE_FROM_AI_SUGGESTION'
} as const;
export type BulkBankTransactionsJobRequestDtoOperationEnum = typeof BulkBankTransactionsJobRequestDtoOperationEnum[keyof typeof BulkBankTransactionsJobRequestDtoOperationEnum];


/**
 * Check if a given object implements the BulkBankTransactionsJobRequestDto interface.
 */
export function instanceOfBulkBankTransactionsJobRequestDto(value: object): value is BulkBankTransactionsJobRequestDto {
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('bankTransactionIds' in value) || value['bankTransactionIds'] === undefined) return false;
    return true;
}

export function BulkBankTransactionsJobRequestDtoFromJSON(json: any): BulkBankTransactionsJobRequestDto {
    return BulkBankTransactionsJobRequestDtoFromJSONTyped(json, false);
}

export function BulkBankTransactionsJobRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkBankTransactionsJobRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'],
        'bankTransactionIds': json['bankTransactionIds'],
    };
}

export function BulkBankTransactionsJobRequestDtoToJSON(json: any): BulkBankTransactionsJobRequestDto {
    return BulkBankTransactionsJobRequestDtoToJSONTyped(json, false);
}

export function BulkBankTransactionsJobRequestDtoToJSONTyped(value?: BulkBankTransactionsJobRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'bankTransactionIds': value['bankTransactionIds'],
    };
}

