/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoriesPageEntityItemsInner
 */
export interface CategoriesPageEntityItemsInner {
    /**
     * Identificador da categoria.
     * @type {string}
     * @memberof CategoriesPageEntityItemsInner
     */
    id: string;
    /**
     * Direção da categoria (IN ou OUT).
     * @type {string}
     * @memberof CategoriesPageEntityItemsInner
     */
    direction: CategoriesPageEntityItemsInnerDirectionEnum;
    /**
     * Índice da categoria.
     * @type {number}
     * @memberof CategoriesPageEntityItemsInner
     */
    index: number;
    /**
     * Nome da categoria.
     * @type {string}
     * @memberof CategoriesPageEntityItemsInner
     */
    name: string;
    /**
     * Slug da categoria.
     * @type {string}
     * @memberof CategoriesPageEntityItemsInner
     */
    slug: string;
    /**
     * Data de criação da categoria.
     * @type {any}
     * @memberof CategoriesPageEntityItemsInner
     */
    createdAt: any | null;
    /**
     * Data de atualização da categoria.
     * @type {any}
     * @memberof CategoriesPageEntityItemsInner
     */
    updatedAt: any | null;
}


/**
 * @export
 */
export const CategoriesPageEntityItemsInnerDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type CategoriesPageEntityItemsInnerDirectionEnum = typeof CategoriesPageEntityItemsInnerDirectionEnum[keyof typeof CategoriesPageEntityItemsInnerDirectionEnum];


/**
 * Check if a given object implements the CategoriesPageEntityItemsInner interface.
 */
export function instanceOfCategoriesPageEntityItemsInner(value: object): value is CategoriesPageEntityItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CategoriesPageEntityItemsInnerFromJSON(json: any): CategoriesPageEntityItemsInner {
    return CategoriesPageEntityItemsInnerFromJSONTyped(json, false);
}

export function CategoriesPageEntityItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesPageEntityItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'direction': json['direction'],
        'index': json['index'],
        'name': json['name'],
        'slug': json['slug'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CategoriesPageEntityItemsInnerToJSON(json: any): CategoriesPageEntityItemsInner {
    return CategoriesPageEntityItemsInnerToJSONTyped(json, false);
}

export function CategoriesPageEntityItemsInnerToJSONTyped(value?: CategoriesPageEntityItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'direction': value['direction'],
        'index': value['index'],
        'name': value['name'],
        'slug': value['slug'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

