/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmFileUploadRequestBodyDto
 */
export interface ConfirmFileUploadRequestBodyDto {
    /**
     * Identificador do arquivo.
     * @type {string}
     * @memberof ConfirmFileUploadRequestBodyDto
     */
    id: string;
    /**
     * Tamanho do arquivo em bytes.
     * @type {number}
     * @memberof ConfirmFileUploadRequestBodyDto
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfirmFileUploadRequestBodyDto
     */
    status: ConfirmFileUploadRequestBodyDtoStatusEnum;
    /**
     * Legenda do arquivo.
     * @type {string}
     * @memberof ConfirmFileUploadRequestBodyDto
     */
    caption?: string | null;
    /**
     * Data de exclusão do arquivo.
     * @type {any}
     * @memberof ConfirmFileUploadRequestBodyDto
     */
    deletedAt?: any | null;
    /**
     * Canal de origem da operação
     * @type {string}
     * @memberof ConfirmFileUploadRequestBodyDto
     */
    channel: ConfirmFileUploadRequestBodyDtoChannelEnum;
}


/**
 * @export
 */
export const ConfirmFileUploadRequestBodyDtoStatusEnum = {
    Failed: 'FAILED',
    Completed: 'COMPLETED'
} as const;
export type ConfirmFileUploadRequestBodyDtoStatusEnum = typeof ConfirmFileUploadRequestBodyDtoStatusEnum[keyof typeof ConfirmFileUploadRequestBodyDtoStatusEnum];

/**
 * @export
 */
export const ConfirmFileUploadRequestBodyDtoChannelEnum = {
    WebApp: 'WEB_APP',
    Whatsapp: 'WHATSAPP',
    System: 'SYSTEM',
    Email: 'EMAIL'
} as const;
export type ConfirmFileUploadRequestBodyDtoChannelEnum = typeof ConfirmFileUploadRequestBodyDtoChannelEnum[keyof typeof ConfirmFileUploadRequestBodyDtoChannelEnum];


/**
 * Check if a given object implements the ConfirmFileUploadRequestBodyDto interface.
 */
export function instanceOfConfirmFileUploadRequestBodyDto(value: object): value is ConfirmFileUploadRequestBodyDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    return true;
}

export function ConfirmFileUploadRequestBodyDtoFromJSON(json: any): ConfirmFileUploadRequestBodyDto {
    return ConfirmFileUploadRequestBodyDtoFromJSONTyped(json, false);
}

export function ConfirmFileUploadRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmFileUploadRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'size': json['size'] == null ? undefined : json['size'],
        'status': json['status'],
        'caption': json['caption'] == null ? undefined : json['caption'],
        'deletedAt': json['deletedAt'] == null ? undefined : json['deletedAt'],
        'channel': json['channel'],
    };
}

export function ConfirmFileUploadRequestBodyDtoToJSON(json: any): ConfirmFileUploadRequestBodyDto {
    return ConfirmFileUploadRequestBodyDtoToJSONTyped(json, false);
}

export function ConfirmFileUploadRequestBodyDtoToJSONTyped(value?: ConfirmFileUploadRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'size': value['size'],
        'status': value['status'],
        'caption': value['caption'],
        'deletedAt': value['deletedAt'],
        'channel': value['channel'],
    };
}

