/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateContactRequestBodyDtoAddress } from './CreateContactRequestBodyDtoAddress';
import {
    CreateContactRequestBodyDtoAddressFromJSON,
    CreateContactRequestBodyDtoAddressFromJSONTyped,
    CreateContactRequestBodyDtoAddressToJSON,
    CreateContactRequestBodyDtoAddressToJSONTyped,
} from './CreateContactRequestBodyDtoAddress';

/**
 * 
 * @export
 * @interface ContactsPageEntityItemsInner
 */
export interface ContactsPageEntityItemsInner {
    /**
     * Identificador do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    id: string;
    /**
     * Identificador da organização dona do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    organization: string;
    /**
     * Identificador do usuário que criou o contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    createdByUser: string;
    /**
     * Identificador da organização que criou o contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    createdByOrganization: string;
    /**
     * Identificador do canal que criou o contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    createdByChannel: ContactsPageEntityItemsInnerCreatedByChannelEnum;
    /**
     * Nome do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    name: string;
    /**
     * Tipos do contato.
     * @type {Array<string>}
     * @memberof ContactsPageEntityItemsInner
     */
    types: Array<ContactsPageEntityItemsInnerTypesEnum>;
    /**
     * Tipo do documento do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    documentType?: ContactsPageEntityItemsInnerDocumentTypeEnum | null;
    /**
     * Documento do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    document?: string | null;
    /**
     * Email do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    email?: string | null;
    /**
     * Telefone do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    phone?: string | null;
    /**
     * Origem do contato.
     * @type {string}
     * @memberof ContactsPageEntityItemsInner
     */
    origin?: ContactsPageEntityItemsInnerOriginEnum | null;
    /**
     * 
     * @type {CreateContactRequestBodyDtoAddress}
     * @memberof ContactsPageEntityItemsInner
     */
    address?: CreateContactRequestBodyDtoAddress | null;
    /**
     * Data de criação do contato.
     * @type {Date}
     * @memberof ContactsPageEntityItemsInner
     */
    createdAt: Date;
    /**
     * Data de atualização do contato.
     * @type {Date}
     * @memberof ContactsPageEntityItemsInner
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const ContactsPageEntityItemsInnerCreatedByChannelEnum = {
    WebApp: 'WEB_APP',
    Whatsapp: 'WHATSAPP'
} as const;
export type ContactsPageEntityItemsInnerCreatedByChannelEnum = typeof ContactsPageEntityItemsInnerCreatedByChannelEnum[keyof typeof ContactsPageEntityItemsInnerCreatedByChannelEnum];

/**
 * @export
 */
export const ContactsPageEntityItemsInnerTypesEnum = {
    Customer: 'CUSTOMER',
    Employee: 'EMPLOYEE',
    Supplier: 'SUPPLIER',
    Partner: 'PARTNER'
} as const;
export type ContactsPageEntityItemsInnerTypesEnum = typeof ContactsPageEntityItemsInnerTypesEnum[keyof typeof ContactsPageEntityItemsInnerTypesEnum];

/**
 * @export
 */
export const ContactsPageEntityItemsInnerDocumentTypeEnum = {
    Cnpj: 'CNPJ',
    Cpf: 'CPF'
} as const;
export type ContactsPageEntityItemsInnerDocumentTypeEnum = typeof ContactsPageEntityItemsInnerDocumentTypeEnum[keyof typeof ContactsPageEntityItemsInnerDocumentTypeEnum];

/**
 * @export
 */
export const ContactsPageEntityItemsInnerOriginEnum = {
    Indication: 'INDICATION',
    Ads: 'ADS',
    OrganicSearch: 'ORGANIC_SEARCH',
    SocialMedia: 'SOCIAL_MEDIA',
    Events: 'EVENTS',
    Partnerships: 'PARTNERSHIPS',
    PhysicalStore: 'PHYSICAL_STORE',
    Other: 'OTHER'
} as const;
export type ContactsPageEntityItemsInnerOriginEnum = typeof ContactsPageEntityItemsInnerOriginEnum[keyof typeof ContactsPageEntityItemsInnerOriginEnum];


/**
 * Check if a given object implements the ContactsPageEntityItemsInner interface.
 */
export function instanceOfContactsPageEntityItemsInner(value: object): value is ContactsPageEntityItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('createdByUser' in value) || value['createdByUser'] === undefined) return false;
    if (!('createdByOrganization' in value) || value['createdByOrganization'] === undefined) return false;
    if (!('createdByChannel' in value) || value['createdByChannel'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ContactsPageEntityItemsInnerFromJSON(json: any): ContactsPageEntityItemsInner {
    return ContactsPageEntityItemsInnerFromJSONTyped(json, false);
}

export function ContactsPageEntityItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactsPageEntityItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization': json['organization'],
        'createdByUser': json['createdByUser'],
        'createdByOrganization': json['createdByOrganization'],
        'createdByChannel': json['createdByChannel'],
        'name': json['name'],
        'types': json['types'],
        'documentType': json['documentType'] == null ? undefined : json['documentType'],
        'document': json['document'] == null ? undefined : json['document'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'address': json['address'] == null ? undefined : CreateContactRequestBodyDtoAddressFromJSON(json['address']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ContactsPageEntityItemsInnerToJSON(json: any): ContactsPageEntityItemsInner {
    return ContactsPageEntityItemsInnerToJSONTyped(json, false);
}

export function ContactsPageEntityItemsInnerToJSONTyped(value?: ContactsPageEntityItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization': value['organization'],
        'createdByUser': value['createdByUser'],
        'createdByOrganization': value['createdByOrganization'],
        'createdByChannel': value['createdByChannel'],
        'name': value['name'],
        'types': value['types'],
        'documentType': value['documentType'],
        'document': value['document'],
        'email': value['email'],
        'phone': value['phone'],
        'origin': value['origin'],
        'address': CreateContactRequestBodyDtoAddressToJSON(value['address']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

