/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryItemEntity
 */
export interface CountryItemEntity {
    /**
     * Identificador do país.
     * @type {string}
     * @memberof CountryItemEntity
     */
    id: string;
    /**
     * Nome do país.
     * @type {string}
     * @memberof CountryItemEntity
     */
    name: string;
}

/**
 * Check if a given object implements the CountryItemEntity interface.
 */
export function instanceOfCountryItemEntity(value: object): value is CountryItemEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CountryItemEntityFromJSON(json: any): CountryItemEntity {
    return CountryItemEntityFromJSONTyped(json, false);
}

export function CountryItemEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryItemEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CountryItemEntityToJSON(json: any): CountryItemEntity {
    return CountryItemEntityToJSONTyped(json, false);
}

export function CountryItemEntityToJSONTyped(value?: CountryItemEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

