/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Categoria da subcategoria.
 * @export
 * @interface CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
 */
export interface CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory {
    /**
     * Identificador da categoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    id: string;
    /**
     * Direção da categoria (IN ou OUT).
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    direction: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryDirectionEnum;
    /**
     * Índice da categoria.
     * @type {number}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    index: number;
    /**
     * Nome da categoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    name: string;
    /**
     * Slug da categoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    slug: string;
    /**
     * Data de criação da categoria.
     * @type {any}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    createdAt: any | null;
    /**
     * Data de atualização da categoria.
     * @type {any}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory
     */
    updatedAt: any | null;
}


/**
 * @export
 */
export const CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryDirectionEnum = typeof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryDirectionEnum[keyof typeof CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryDirectionEnum];


/**
 * Check if a given object implements the CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory interface.
 */
export function instanceOfCreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory(value: object): value is CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory {
    return CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'direction': json['direction'],
        'index': json['index'],
        'name': json['name'],
        'slug': json['slug'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory {
    return CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSONTyped(value?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'direction': value['direction'],
        'index': value['index'],
        'name': value['name'],
        'slug': value['slug'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

