/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedFilesInner } from './CreateFinancialRecordRequestBodyDtoPopulatedFilesInner';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedFilesInner';
import type { CreateFinancialRecordRequestBodyDtoPopulatedTagsInner } from './CreateFinancialRecordRequestBodyDtoPopulatedTagsInner';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedTagsInner';
import type { CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory } from './CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory';
import {
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON,
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSONTyped,
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON,
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSONTyped,
} from './CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory';
import type { CreateFinancialRecordRequestBodyDtoPopulatedContact } from './CreateFinancialRecordRequestBodyDtoPopulatedContact';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedContactToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedContactToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedContact';

/**
 * 
 * @export
 * @interface CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
 */
export interface CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner {
    /**
     * Direção do lançamento (entrada/saída).
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    direction: CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    firstOccurrenceDate: string;
    /**
     * Descrição do lançamento.
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    description: string;
    /**
     * Identificador do contato relacionado.
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    contact?: string;
    /**
     * Identificador da subcategoria.
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    subcategory: string;
    /**
     * 
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    amount: string;
    /**
     * Tags relacionadas.
     * @type {Array<string>}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    tags?: Array<string>;
    /**
     * Arquivos anexados.
     * @type {Array<string>}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    files?: Array<string>;
    /**
     * Frequência de repetição do lançamento.
     * @type {string}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    frequency: CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFrequencyEnum;
    /**
     * Dia de repetição do lançamento.
     * @type {number}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    repetitionDay: number;
    /**
     * Mês de repetição do lançamento.
     * @type {number}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    repetitionMonth?: number | null;
    /**
     * Indica se o lançamento será apenas em dias úteis.
     * @type {boolean}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    onlyBusinessDays?: boolean;
    /**
     * Indica se o lançamento será completado automaticamente.
     * @type {boolean}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    automaticCompletion?: boolean;
    /**
     * Indica se o lançamento recorrente está ativo.
     * @type {boolean}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    isActive?: boolean;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedContact}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    populatedContact?: CreateFinancialRecordRequestBodyDtoPopulatedContact | null;
    /**
     * Tags relacionadas.
     * @type {Array<CreateFinancialRecordRequestBodyDtoPopulatedTagsInner>}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    populatedTags?: Array<CreateFinancialRecordRequestBodyDtoPopulatedTagsInner> | null;
    /**
     * 
     * @type {CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    populatedSubcategory?: CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory | null;
    /**
     * Arquivos anexados.
     * @type {Array<CreateFinancialRecordRequestBodyDtoPopulatedFilesInner>}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    populatedFiles?: Array<CreateFinancialRecordRequestBodyDtoPopulatedFilesInner>;
    /**
     * 
     * @type {number}
     * @memberof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner
     */
    searchScore?: number;
}


/**
 * @export
 */
export const CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerDirectionEnum = typeof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerDirectionEnum[keyof typeof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerDirectionEnum];

/**
 * @export
 */
export const CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFrequencyEnum = {
    Weekly: 'WEEKLY',
    Monthly: 'MONTHLY',
    Yearly: 'YEARLY'
} as const;
export type CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFrequencyEnum = typeof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFrequencyEnum[keyof typeof CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFrequencyEnum];


/**
 * Check if a given object implements the CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner interface.
 */
export function instanceOfCreateManyRecurringFinancialRecordsRequestBodyDtoDataInner(value: object): value is CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner {
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('firstOccurrenceDate' in value) || value['firstOccurrenceDate'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    if (!('repetitionDay' in value) || value['repetitionDay'] === undefined) return false;
    return true;
}

export function CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFromJSON(json: any): CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner {
    return CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFromJSONTyped(json, false);
}

export function CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'],
        'firstOccurrenceDate': json['firstOccurrenceDate'],
        'description': json['description'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'subcategory': json['subcategory'],
        'amount': json['amount'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'files': json['files'] == null ? undefined : json['files'],
        'frequency': json['frequency'],
        'repetitionDay': json['repetitionDay'],
        'repetitionMonth': json['repetitionMonth'] == null ? undefined : json['repetitionMonth'],
        'onlyBusinessDays': json['onlyBusinessDays'] == null ? undefined : json['onlyBusinessDays'],
        'automaticCompletion': json['automaticCompletion'] == null ? undefined : json['automaticCompletion'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'populatedContact': json['populatedContact'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSON(json['populatedContact']),
        'populatedTags': json['populatedTags'] == null ? undefined : ((json['populatedTags'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerFromJSON)),
        'populatedSubcategory': json['populatedSubcategory'] == null ? undefined : CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON(json['populatedSubcategory']),
        'populatedFiles': json['populatedFiles'] == null ? undefined : ((json['populatedFiles'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSON)),
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
    };
}

export function CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerToJSON(json: any): CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner {
    return CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerToJSONTyped(json, false);
}

export function CreateManyRecurringFinancialRecordsRequestBodyDtoDataInnerToJSONTyped(value?: CreateManyRecurringFinancialRecordsRequestBodyDtoDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'direction': value['direction'],
        'firstOccurrenceDate': value['firstOccurrenceDate'],
        'description': value['description'],
        'contact': value['contact'],
        'subcategory': value['subcategory'],
        'amount': value['amount'],
        'tags': value['tags'],
        'files': value['files'],
        'frequency': value['frequency'],
        'repetitionDay': value['repetitionDay'],
        'repetitionMonth': value['repetitionMonth'],
        'onlyBusinessDays': value['onlyBusinessDays'],
        'automaticCompletion': value['automaticCompletion'],
        'isActive': value['isActive'],
        'populatedContact': CreateFinancialRecordRequestBodyDtoPopulatedContactToJSON(value['populatedContact']),
        'populatedTags': value['populatedTags'] == null ? undefined : ((value['populatedTags'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerToJSON)),
        'populatedSubcategory': CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON(value['populatedSubcategory']),
        'populatedFiles': value['populatedFiles'] == null ? undefined : ((value['populatedFiles'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSON)),
        'searchScore': value['searchScore'],
    };
}

