/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFilterRequestDto
 */
export interface CreateFilterRequestDto {
    /**
     * Recurso ao qual o filtro se aplica.
     * @type {string}
     * @memberof CreateFilterRequestDto
     */
    resource: CreateFilterRequestDtoResourceEnum;
    /**
     * Consulta do filtro como um objeto de chave-valor.
     * @type {{ [key: string]: string; }}
     * @memberof CreateFilterRequestDto
     */
    query: { [key: string]: string; };
}


/**
 * @export
 */
export const CreateFilterRequestDtoResourceEnum = {
    FinancialRecord: 'FINANCIAL_RECORD',
    BankTransaction: 'BANK_TRANSACTION'
} as const;
export type CreateFilterRequestDtoResourceEnum = typeof CreateFilterRequestDtoResourceEnum[keyof typeof CreateFilterRequestDtoResourceEnum];


/**
 * Check if a given object implements the CreateFilterRequestDto interface.
 */
export function instanceOfCreateFilterRequestDto(value: object): value is CreateFilterRequestDto {
    if (!('resource' in value) || value['resource'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function CreateFilterRequestDtoFromJSON(json: any): CreateFilterRequestDto {
    return CreateFilterRequestDtoFromJSONTyped(json, false);
}

export function CreateFilterRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFilterRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'resource': json['resource'],
        'query': json['query'],
    };
}

export function CreateFilterRequestDtoToJSON(json: any): CreateFilterRequestDto {
    return CreateFilterRequestDtoToJSONTyped(json, false);
}

export function CreateFilterRequestDtoToJSONTyped(value?: CreateFilterRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource': value['resource'],
        'query': value['query'],
    };
}

