/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner
 */
export interface CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner {
    /**
     * Nome do arquivo.
     * @type {string}
     * @memberof CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner
     */
    name: string;
    /**
     * URL do arquivo.
     * @type {string}
     * @memberof CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner
     */
    url: string;
    /**
     * Tipo MIME do arquivo.
     * @type {string}
     * @memberof CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner
     */
    mimeType: string;
}

/**
 * Check if a given object implements the CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner interface.
 */
export function instanceOfCreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner(value: object): value is CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerFromJSON(json: any): CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner {
    return CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerFromJSONTyped(json, false);
}

export function CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'mimeType': json['mimeType'],
    };
}

export function CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerToJSON(json: any): CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner {
    return CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerToJSONTyped(json, false);
}

export function CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerToJSONTyped(value?: CreateInboxRecordRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'mimeType': value['mimeType'],
    };
}

