/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateContactRequestBodyDtoAddress } from './CreateContactRequestBodyDtoAddress';
import {
    CreateContactRequestBodyDtoAddressFromJSON,
    CreateContactRequestBodyDtoAddressFromJSONTyped,
    CreateContactRequestBodyDtoAddressToJSON,
    CreateContactRequestBodyDtoAddressToJSONTyped,
} from './CreateContactRequestBodyDtoAddress';

/**
 * Contato do lançamento.
 * @export
 * @interface CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
 */
export interface CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact {
    /**
     * Identificador do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    id: string;
    /**
     * Identificador da organização dona do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    ownerOrganization: string;
    /**
     * Nome do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    name: string;
    /**
     * Tipos do contato.
     * @type {Array<string>}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    types: Array<CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactTypesEnum>;
    /**
     * Tipo do documento do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    documentType?: CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactDocumentTypeEnum | null;
    /**
     * Documento do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    document: string | null;
    /**
     * Email do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    email: string | null;
    /**
     * Telefone do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    phone: string | null;
    /**
     * Chaves pix do contato.
     * @type {Array<string>}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    pixKeys: Array<string>;
    /**
     * Data de nascimento do contato.
     * @type {any}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    birthDate?: any | null;
    /**
     * Origem do contato.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    origin?: CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactOriginEnum | null;
    /**
     * 
     * @type {CreateContactRequestBodyDtoAddress}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    address?: CreateContactRequestBodyDtoAddress | null;
    /**
     * Indica se o contato é o contato não identificado.
     * @type {boolean}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    isNotIdentified: boolean;
    /**
     * Pontuação de busca do contato.
     * @type {number}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    searchScore?: number | null;
    /**
     * Data de criação do contato.
     * @type {any}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    createdAt: any | null;
    /**
     * Data de atualização do contato.
     * @type {any}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact
     */
    updatedAt: any | null;
}


/**
 * @export
 */
export const CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactTypesEnum = {
    Customer: 'CUSTOMER',
    Employee: 'EMPLOYEE',
    Supplier: 'SUPPLIER',
    Partner: 'PARTNER'
} as const;
export type CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactTypesEnum = typeof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactTypesEnum[keyof typeof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactTypesEnum];

/**
 * @export
 */
export const CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactDocumentTypeEnum = {
    Cnpj: 'CNPJ',
    Cpf: 'CPF'
} as const;
export type CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactDocumentTypeEnum = typeof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactDocumentTypeEnum[keyof typeof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactDocumentTypeEnum];

/**
 * @export
 */
export const CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactOriginEnum = {
    Indication: 'INDICATION',
    Ads: 'ADS',
    OrganicSearch: 'ORGANIC_SEARCH',
    SocialMedia: 'SOCIAL_MEDIA',
    Events: 'EVENTS',
    Partnerships: 'PARTNERSHIPS',
    PhysicalStore: 'PHYSICAL_STORE',
    Other: 'OTHER'
} as const;
export type CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactOriginEnum = typeof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactOriginEnum[keyof typeof CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactOriginEnum];


/**
 * Check if a given object implements the CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact interface.
 */
export function instanceOfCreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact(value: object): value is CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('document' in value) || value['document'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('pixKeys' in value) || value['pixKeys'] === undefined) return false;
    if (!('isNotIdentified' in value) || value['isNotIdentified'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactFromJSON(json: any): CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact {
    return CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactFromJSONTyped(json, false);
}

export function CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'name': json['name'],
        'types': json['types'],
        'documentType': json['documentType'] == null ? undefined : json['documentType'],
        'document': json['document'],
        'email': json['email'],
        'phone': json['phone'],
        'pixKeys': json['pixKeys'],
        'birthDate': json['birthDate'] == null ? undefined : json['birthDate'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'address': json['address'] == null ? undefined : CreateContactRequestBodyDtoAddressFromJSON(json['address']),
        'isNotIdentified': json['isNotIdentified'],
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactToJSON(json: any): CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact {
    return CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactToJSONTyped(json, false);
}

export function CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContactToJSONTyped(value?: CreateInstallmentFinancialRecordRequestBodyDtoPopulatedContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'name': value['name'],
        'types': value['types'],
        'documentType': value['documentType'],
        'document': value['document'],
        'email': value['email'],
        'phone': value['phone'],
        'pixKeys': value['pixKeys'],
        'birthDate': value['birthDate'],
        'origin': value['origin'],
        'address': CreateContactRequestBodyDtoAddressToJSON(value['address']),
        'isNotIdentified': value['isNotIdentified'],
        'searchScore': value['searchScore'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

