/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreatePostRequestBodyDtoTagsInnerOneOf } from './CreatePostRequestBodyDtoTagsInnerOneOf';
import {
    instanceOfCreatePostRequestBodyDtoTagsInnerOneOf,
    CreatePostRequestBodyDtoTagsInnerOneOfFromJSON,
    CreatePostRequestBodyDtoTagsInnerOneOfFromJSONTyped,
    CreatePostRequestBodyDtoTagsInnerOneOfToJSON,
} from './CreatePostRequestBodyDtoTagsInnerOneOf';
import type { string } from './string';
import {
    instanceOfstring,
    stringFromJSON,
    stringFromJSONTyped,
    stringToJSON,
} from './string';

/**
 * @type CreatePostRequestBodyDtoTagsInner
 * 
 * @export
 */
export type CreatePostRequestBodyDtoTagsInner = CreatePostRequestBodyDtoTagsInnerOneOf | string;

export function CreatePostRequestBodyDtoTagsInnerFromJSON(json: any): CreatePostRequestBodyDtoTagsInner {
    return CreatePostRequestBodyDtoTagsInnerFromJSONTyped(json, false);
}

export function CreatePostRequestBodyDtoTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostRequestBodyDtoTagsInner {
    if (json == null) {
        return json;
    }
    if (instanceOfCreatePostRequestBodyDtoTagsInnerOneOf(json)) {
        return CreatePostRequestBodyDtoTagsInnerOneOfFromJSONTyped(json, true);
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CreatePostRequestBodyDtoTagsInnerToJSON(json: any): any {
    return CreatePostRequestBodyDtoTagsInnerToJSONTyped(json, false);
}

export function CreatePostRequestBodyDtoTagsInnerToJSONTyped(value?: CreatePostRequestBodyDtoTagsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCreatePostRequestBodyDtoTagsInnerOneOf(value)) {
        return CreatePostRequestBodyDtoTagsInnerOneOfToJSON(value as CreatePostRequestBodyDtoTagsInnerOneOf);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

