/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution } from './CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution';
import type { CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatus } from './CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatus';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatus';

/**
 * 
 * @export
 * @interface CreateBankAccountRequestBodyDto
 */
export interface CreateBankAccountRequestBodyDto {
    /**
     * Nome da conta bancária.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    name: string;
    /**
     * Tipo da conta bancária.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    type: CreateBankAccountRequestBodyDtoTypeEnum;
    /**
     * Número da conta ou cartão.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    number: string;
    /**
     * Indica se a conta deve ser considerada nos cálculos de fluxo de caixa.
     * @type {boolean}
     * @memberof CreateBankAccountRequestBodyDto
     */
    considerInCashFlow?: boolean;
    /**
     * Indica se a conta é automática ou manual.
     * @type {boolean}
     * @memberof CreateBankAccountRequestBodyDto
     */
    isAutomatic: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateBankAccountRequestBodyDto
     */
    isDefault?: boolean;
    /**
     * Data do saldo inicial da conta bancária.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    initialBalanceDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    initialBalanceAmount?: string | null;
    /**
     * Instituição financeira.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    institution?: string | null;
    /**
     * Nome da instituição financeira.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    institutionName?: string | null;
    /**
     * Fornecedor da conta bancária.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    provider?: CreateBankAccountRequestBodyDtoProviderEnum | null;
    /**
     * Identificador da conta bancária no fornecedor.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    providerAccountId?: string | null;
    /**
     * Identificador do item de conexão do fornecedor.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    providerItemId?: string | null;
    /**
     * Pontuação de busca.
     * @type {number}
     * @memberof CreateBankAccountRequestBodyDto
     */
    searchScore?: number | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution}
     * @memberof CreateBankAccountRequestBodyDto
     */
    populatedInstitution?: CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatus}
     * @memberof CreateBankAccountRequestBodyDto
     */
    populatedAutomaticStatus?: CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatus | null;
    /**
     * Data de importação da conta bancária.
     * @type {any}
     * @memberof CreateBankAccountRequestBodyDto
     */
    importedAt?: any | null;
    /**
     * Origem da importação da conta bancária.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    importedBy?: string | null;
    /**
     * Identificador externo da conta bancária.
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    externalId?: string | null;
    /**
     * Canal de origem da operação
     * @type {string}
     * @memberof CreateBankAccountRequestBodyDto
     */
    channel: CreateBankAccountRequestBodyDtoChannelEnum;
}


/**
 * @export
 */
export const CreateBankAccountRequestBodyDtoTypeEnum = {
    Money: 'MONEY',
    Checking: 'CHECKING',
    Savings: 'SAVINGS',
    CreditCard: 'CREDIT_CARD',
    Application: 'APPLICATION',
    Other: 'OTHER'
} as const;
export type CreateBankAccountRequestBodyDtoTypeEnum = typeof CreateBankAccountRequestBodyDtoTypeEnum[keyof typeof CreateBankAccountRequestBodyDtoTypeEnum];

/**
 * @export
 */
export const CreateBankAccountRequestBodyDtoProviderEnum = {
    Pluggy: 'PLUGGY',
    Ofx: 'OFX',
    Other: 'OTHER'
} as const;
export type CreateBankAccountRequestBodyDtoProviderEnum = typeof CreateBankAccountRequestBodyDtoProviderEnum[keyof typeof CreateBankAccountRequestBodyDtoProviderEnum];

/**
 * @export
 */
export const CreateBankAccountRequestBodyDtoChannelEnum = {
    WebApp: 'WEB_APP',
    Whatsapp: 'WHATSAPP',
    System: 'SYSTEM',
    Email: 'EMAIL'
} as const;
export type CreateBankAccountRequestBodyDtoChannelEnum = typeof CreateBankAccountRequestBodyDtoChannelEnum[keyof typeof CreateBankAccountRequestBodyDtoChannelEnum];


/**
 * Check if a given object implements the CreateBankAccountRequestBodyDto interface.
 */
export function instanceOfCreateBankAccountRequestBodyDto(value: object): value is CreateBankAccountRequestBodyDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('isAutomatic' in value) || value['isAutomatic'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    return true;
}

export function CreateBankAccountRequestBodyDtoFromJSON(json: any): CreateBankAccountRequestBodyDto {
    return CreateBankAccountRequestBodyDtoFromJSONTyped(json, false);
}

export function CreateBankAccountRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBankAccountRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'number': json['number'],
        'considerInCashFlow': json['considerInCashFlow'] == null ? undefined : json['considerInCashFlow'],
        'isAutomatic': json['isAutomatic'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'initialBalanceDate': json['initialBalanceDate'] == null ? undefined : json['initialBalanceDate'],
        'initialBalanceAmount': json['initialBalanceAmount'] == null ? undefined : json['initialBalanceAmount'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'institutionName': json['institutionName'] == null ? undefined : json['institutionName'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerAccountId': json['providerAccountId'] == null ? undefined : json['providerAccountId'],
        'providerItemId': json['providerItemId'] == null ? undefined : json['providerItemId'],
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
        'populatedInstitution': json['populatedInstitution'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionFromJSON(json['populatedInstitution']),
        'populatedAutomaticStatus': json['populatedAutomaticStatus'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusFromJSON(json['populatedAutomaticStatus']),
        'importedAt': json['importedAt'] == null ? undefined : json['importedAt'],
        'importedBy': json['importedBy'] == null ? undefined : json['importedBy'],
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'channel': json['channel'],
    };
}

export function CreateBankAccountRequestBodyDtoToJSON(json: any): CreateBankAccountRequestBodyDto {
    return CreateBankAccountRequestBodyDtoToJSONTyped(json, false);
}

export function CreateBankAccountRequestBodyDtoToJSONTyped(value?: CreateBankAccountRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'number': value['number'],
        'considerInCashFlow': value['considerInCashFlow'],
        'isAutomatic': value['isAutomatic'],
        'isDefault': value['isDefault'],
        'initialBalanceDate': value['initialBalanceDate'],
        'initialBalanceAmount': value['initialBalanceAmount'],
        'institution': value['institution'],
        'institutionName': value['institutionName'],
        'provider': value['provider'],
        'providerAccountId': value['providerAccountId'],
        'providerItemId': value['providerItemId'],
        'searchScore': value['searchScore'],
        'populatedInstitution': CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionToJSON(value['populatedInstitution']),
        'populatedAutomaticStatus': CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusToJSON(value['populatedAutomaticStatus']),
        'importedAt': value['importedAt'],
        'importedBy': value['importedBy'],
        'externalId': value['externalId'],
        'channel': value['channel'],
    };
}

