/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessage } from './CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessage';
import {
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFromJSON,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFromJSONTyped,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageToJSON,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageToJSONTyped,
} from './CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessage';
import type { CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInner } from './CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInner';
import {
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInnerFromJSON,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInnerFromJSONTyped,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInnerToJSON,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInnerToJSONTyped,
} from './CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInner';

/**
 * Dados da mensagem WhatsApp.
 * @export
 * @interface CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData
 */
export interface CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData {
    /**
     * 
     * @type {CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessage}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData
     */
    currentMessage: CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessage;
    /**
     * Últimas mensagens.
     * @type {Array<CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInner>}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData
     */
    lastMessages: Array<CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInner>;
}

/**
 * Check if a given object implements the CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData interface.
 */
export function instanceOfCreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData(value: object): value is CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData {
    if (!('currentMessage' in value) || value['currentMessage'] === undefined) return false;
    if (!('lastMessages' in value) || value['lastMessages'] === undefined) return false;
    return true;
}

export function CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataFromJSON(json: any): CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData {
    return CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataFromJSONTyped(json, false);
}

export function CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData {
    if (json == null) {
        return json;
    }
    return {
        
        'currentMessage': CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFromJSON(json['currentMessage']),
        'lastMessages': ((json['lastMessages'] as Array<any>).map(CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInnerFromJSON)),
    };
}

export function CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataToJSON(json: any): CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData {
    return CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataToJSONTyped(json, false);
}

export function CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataToJSONTyped(value?: CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentMessage': CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageToJSON(value['currentMessage']),
        'lastMessages': ((value['lastMessages'] as Array<any>).map(CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataLastMessagesInnerToJSON)),
    };
}

