/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCustomerRequestBodyDto
 */
export interface CreateCustomerRequestBodyDto {
    /**
     * Nome do customer.
     * @type {string}
     * @memberof CreateCustomerRequestBodyDto
     */
    name: string;
    /**
     * Descrição do customer.
     * @type {string}
     * @memberof CreateCustomerRequestBodyDto
     */
    description?: string | null;
    /**
     * Tipo do customer.
     * @type {string}
     * @memberof CreateCustomerRequestBodyDto
     */
    type: CreateCustomerRequestBodyDtoTypeEnum;
    /**
     * Identificadores das organizações filhas (clerkId).
     * @type {Array<string>}
     * @memberof CreateCustomerRequestBodyDto
     */
    childrenOrganizationsClerkIds?: Array<string>;
    /**
     * Data inicial do customer.
     * @type {any}
     * @memberof CreateCustomerRequestBodyDto
     */
    initialDate?: any | null;
}


/**
 * @export
 */
export const CreateCustomerRequestBodyDtoTypeEnum = {
    BpoOffice: 'BPO_OFFICE',
    Company: 'COMPANY'
} as const;
export type CreateCustomerRequestBodyDtoTypeEnum = typeof CreateCustomerRequestBodyDtoTypeEnum[keyof typeof CreateCustomerRequestBodyDtoTypeEnum];


/**
 * Check if a given object implements the CreateCustomerRequestBodyDto interface.
 */
export function instanceOfCreateCustomerRequestBodyDto(value: object): value is CreateCustomerRequestBodyDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateCustomerRequestBodyDtoFromJSON(json: any): CreateCustomerRequestBodyDto {
    return CreateCustomerRequestBodyDtoFromJSONTyped(json, false);
}

export function CreateCustomerRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomerRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
        'childrenOrganizationsClerkIds': json['childrenOrganizationsClerkIds'] == null ? undefined : json['childrenOrganizationsClerkIds'],
        'initialDate': json['initialDate'] == null ? undefined : json['initialDate'],
    };
}

export function CreateCustomerRequestBodyDtoToJSON(json: any): CreateCustomerRequestBodyDto {
    return CreateCustomerRequestBodyDtoToJSONTyped(json, false);
}

export function CreateCustomerRequestBodyDtoToJSONTyped(value?: CreateCustomerRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'childrenOrganizationsClerkIds': value['childrenOrganizationsClerkIds'],
        'initialDate': value['initialDate'],
    };
}

