/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Conta bancária da movimentação financeira.
 * @export
 * @interface CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
 */
export interface CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount {
    /**
     * Identificador da conta bancária.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    id: string;
    /**
     * Identificador da organização dona da conta bancária.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    ownerOrganization: string;
    /**
     * Nome da conta bancária.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    name: string;
    /**
     * Tipo da conta bancária.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    type: CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountTypeEnum;
    /**
     * Número da conta ou cartão.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    number: string;
    /**
     * Indica se a conta é automática ou manual.
     * @type {boolean}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    isAutomatic: boolean;
    /**
     * Indica se a conta é a padrão.
     * @type {boolean}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    isDefault: boolean;
    /**
     * Data do saldo inicial.
     * @type {any}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    initialBalanceDate?: any | null;
    /**
     * Valor do saldo inicial.
     * @type {number}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    initialBalanceAmount?: number | null;
    /**
     * Instituição financeira.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    institution: string;
    /**
     * Indica se a conta está ativa.
     * @type {boolean}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    active: boolean;
    /**
     * Fornecedor da conta bancária.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    provider?: CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountProviderEnum | null;
    /**
     * Identificador da conta bancária no fornecedor.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    providerAccountId?: string | null;
    /**
     * Identificador do item de conexão do fornecedor.
     * @type {string}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    providerItemId?: string | null;
    /**
     * Data de criação da conta bancária.
     * @type {any}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    createdAt: any | null;
    /**
     * Data de atualização da conta bancária.
     * @type {any}
     * @memberof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount
     */
    updatedAt: any | null;
}


/**
 * @export
 */
export const CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountTypeEnum = {
    Money: 'MONEY',
    Checking: 'CHECKING',
    Savings: 'SAVINGS',
    CreditCard: 'CREDIT_CARD',
    Application: 'APPLICATION',
    Other: 'OTHER'
} as const;
export type CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountTypeEnum = typeof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountTypeEnum[keyof typeof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountTypeEnum];

/**
 * @export
 */
export const CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountProviderEnum = {
    Pluggy: 'PLUGGY',
    Ofx: 'OFX',
    Other: 'OTHER'
} as const;
export type CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountProviderEnum = typeof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountProviderEnum[keyof typeof CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountProviderEnum];


/**
 * Check if a given object implements the CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount interface.
 */
export function instanceOfCreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount(value: object): value is CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('isAutomatic' in value) || value['isAutomatic'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('institution' in value) || value['institution'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountFromJSON(json: any): CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount {
    return CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountFromJSONTyped(json, false);
}

export function CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'name': json['name'],
        'type': json['type'],
        'number': json['number'],
        'isAutomatic': json['isAutomatic'],
        'isDefault': json['isDefault'],
        'initialBalanceDate': json['initialBalanceDate'] == null ? undefined : json['initialBalanceDate'],
        'initialBalanceAmount': json['initialBalanceAmount'] == null ? undefined : json['initialBalanceAmount'],
        'institution': json['institution'],
        'active': json['active'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerAccountId': json['providerAccountId'] == null ? undefined : json['providerAccountId'],
        'providerItemId': json['providerItemId'] == null ? undefined : json['providerItemId'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountToJSON(json: any): CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount {
    return CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountToJSONTyped(json, false);
}

export function CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccountToJSONTyped(value?: CreateOrUpdateBankTransactionRequestBodyDtoPopulatedBankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'name': value['name'],
        'type': value['type'],
        'number': value['number'],
        'isAutomatic': value['isAutomatic'],
        'isDefault': value['isDefault'],
        'initialBalanceDate': value['initialBalanceDate'],
        'initialBalanceAmount': value['initialBalanceAmount'],
        'institution': value['institution'],
        'active': value['active'],
        'provider': value['provider'],
        'providerAccountId': value['providerAccountId'],
        'providerItemId': value['providerItemId'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

