/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePostRequestBodyDtoAuthor } from './CreatePostRequestBodyDtoAuthor';
import {
    CreatePostRequestBodyDtoAuthorFromJSON,
    CreatePostRequestBodyDtoAuthorFromJSONTyped,
    CreatePostRequestBodyDtoAuthorToJSON,
    CreatePostRequestBodyDtoAuthorToJSONTyped,
} from './CreatePostRequestBodyDtoAuthor';

/**
 * 
 * @export
 * @interface CreatePostRequestBodyDto
 */
export interface CreatePostRequestBodyDto {
    /**
     * 
     * @type {CreatePostRequestBodyDtoAuthor}
     * @memberof CreatePostRequestBodyDto
     */
    author?: CreatePostRequestBodyDtoAuthor | null;
    /**
     * Título do post.
     * @type {string}
     * @memberof CreatePostRequestBodyDto
     */
    title: string;
    /**
     * Conteúdo do post.
     * @type {string}
     * @memberof CreatePostRequestBodyDto
     */
    content: string;
    /**
     * Status de publicação do post.
     * @type {boolean}
     * @memberof CreatePostRequestBodyDto
     */
    published: boolean;
    /**
     * Data de publicação do post.
     * @type {Date}
     * @memberof CreatePostRequestBodyDto
     */
    publishedAt?: Date | null;
}

/**
 * Check if a given object implements the CreatePostRequestBodyDto interface.
 */
export function instanceOfCreatePostRequestBodyDto(value: object): value is CreatePostRequestBodyDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('published' in value) || value['published'] === undefined) return false;
    return true;
}

export function CreatePostRequestBodyDtoFromJSON(json: any): CreatePostRequestBodyDto {
    return CreatePostRequestBodyDtoFromJSONTyped(json, false);
}

export function CreatePostRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : CreatePostRequestBodyDtoAuthorFromJSON(json['author']),
        'title': json['title'],
        'content': json['content'],
        'published': json['published'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
    };
}

export function CreatePostRequestBodyDtoToJSON(json: any): CreatePostRequestBodyDto {
    return CreatePostRequestBodyDtoToJSONTyped(json, false);
}

export function CreatePostRequestBodyDtoToJSONTyped(value?: CreatePostRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': CreatePostRequestBodyDtoAuthorToJSON(value['author']),
        'title': value['title'],
        'content': value['content'],
        'published': value['published'],
        'publishedAt': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
    };
}

