/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Erro da sincronização da conta bancária.
 * @export
 * @interface CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError
 */
export interface CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError {
    /**
     * Código de erro da sincronização da conta bancária.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError
     */
    code?: string | null;
    /**
     * Mensagem de erro da sincronização da conta bancária.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError
     */
    message?: string | null;
}

/**
 * Check if a given object implements the CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError interface.
 */
export function instanceOfCreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError(value: object): value is CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError {
    return true;
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusErrorFromJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError {
    return CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusErrorFromJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusErrorToJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError {
    return CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusErrorToJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusErrorToJSONTyped(value?: CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedAutomaticStatusError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

