/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory';

/**
 * Subcategoria do lançamento.
 * @export
 * @interface CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
 */
export interface CreateFinancialRecordRequestBodyDtoPopulatedSubcategory {
    /**
     * Identificador da subcategoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    id: string;
    /**
     * Identificador da organização dona da subcategoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    ownerOrganization: string;
    /**
     * Nome da subcategoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    name: string;
    /**
     * Slug da subcategoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    slug: string;
    /**
     * Índice da subcategoria.
     * @type {number}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    index: number;
    /**
     * Identificador da categoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    category: string;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    populatedCategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory | null;
    /**
     * Identificador da subcategoria normalizada.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    normalizedSubcategory?: string | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    populatedNormalizedSubcategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory | null;
    /**
     * Indica se a subcategoria deve ser exibida no DRE.
     * @type {boolean}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    considerInDre: boolean;
    /**
     * Descrição da subcategoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    description: string;
    /**
     * Indica se a subcategoria está ativa.
     * @type {boolean}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    active?: boolean;
    /**
     * Pontuação de busca da subcategoria.
     * @type {number}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    searchScore?: number | null;
    /**
     * Data de criação da subcategoria.
     * @type {any}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    createdAt: any | null;
    /**
     * Data de atualização da subcategoria.
     * @type {any}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    updatedAt: any | null;
    /**
     * Data de importação da subcategoria.
     * @type {any}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    importedAt?: any | null;
    /**
     * Origem da importação da subcategoria.
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedSubcategory
     */
    importedBy?: string | null;
}

/**
 * Check if a given object implements the CreateFinancialRecordRequestBodyDtoPopulatedSubcategory interface.
 */
export function instanceOfCreateFinancialRecordRequestBodyDtoPopulatedSubcategory(value: object): value is CreateFinancialRecordRequestBodyDtoPopulatedSubcategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('considerInDre' in value) || value['considerInDre'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedSubcategory {
    return CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinancialRecordRequestBodyDtoPopulatedSubcategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'name': json['name'],
        'slug': json['slug'],
        'index': json['index'],
        'category': json['category'],
        'populatedCategory': json['populatedCategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON(json['populatedCategory']),
        'normalizedSubcategory': json['normalizedSubcategory'] == null ? undefined : json['normalizedSubcategory'],
        'populatedNormalizedSubcategory': json['populatedNormalizedSubcategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSON(json['populatedNormalizedSubcategory']),
        'considerInDre': json['considerInDre'],
        'description': json['description'],
        'active': json['active'] == null ? undefined : json['active'],
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'importedAt': json['importedAt'] == null ? undefined : json['importedAt'],
        'importedBy': json['importedBy'] == null ? undefined : json['importedBy'],
    };
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedSubcategory {
    return CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSONTyped(value?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'name': value['name'],
        'slug': value['slug'],
        'index': value['index'],
        'category': value['category'],
        'populatedCategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON(value['populatedCategory']),
        'normalizedSubcategory': value['normalizedSubcategory'],
        'populatedNormalizedSubcategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSON(value['populatedNormalizedSubcategory']),
        'considerInDre': value['considerInDre'],
        'description': value['description'],
        'active': value['active'],
        'searchScore': value['searchScore'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'importedAt': value['importedAt'],
        'importedBy': value['importedBy'],
    };
}

