/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateQueryRequestDto
 */
export interface CreateQueryRequestDto {
    /**
     * Dados da consulta como um objeto de chave-valor.
     * @type {{ [key: string]: string; }}
     * @memberof CreateQueryRequestDto
     */
    data: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateQueryRequestDto interface.
 */
export function instanceOfCreateQueryRequestDto(value: object): value is CreateQueryRequestDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateQueryRequestDtoFromJSON(json: any): CreateQueryRequestDto {
    return CreateQueryRequestDtoFromJSONTyped(json, false);
}

export function CreateQueryRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateQueryRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function CreateQueryRequestDtoToJSON(json: any): CreateQueryRequestDto {
    return CreateQueryRequestDtoToJSONTyped(json, false);
}

export function CreateQueryRequestDtoToJSONTyped(value?: CreateQueryRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

