/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner
 */
export interface CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner {
    /**
     * Data de vencimento da parcela.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner
     */
    dueDate: string;
    /**
     * Valor da parcela.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner
     */
    amount: string;
    /**
     * Descrição personalizada da parcela.
     * @type {string}
     * @memberof CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner interface.
 */
export function instanceOfCreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner(value: object): value is CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner {
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInnerFromJSON(json: any): CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner {
    return CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInnerFromJSONTyped(json, false);
}

export function CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'dueDate': json['dueDate'],
        'amount': json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInnerToJSON(json: any): CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner {
    return CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInnerToJSONTyped(json, false);
}

export function CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInnerToJSONTyped(value?: CreateInstallmentFinancialRecordRequestBodyDtoInstallmentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dueDate': value['dueDate'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

