/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationEntityPopulatedSubscriptionStatusHistoryInner } from './OrganizationEntityPopulatedSubscriptionStatusHistoryInner';
import {
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerFromJSON,
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerFromJSONTyped,
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerToJSON,
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerToJSONTyped,
} from './OrganizationEntityPopulatedSubscriptionStatusHistoryInner';

/**
 * 
 * @export
 * @interface CreateSubscriptionRequestBodyDto
 */
export interface CreateSubscriptionRequestBodyDto {
    /**
     * Identificador da organização dona da subscription.
     * @type {string}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    ownerOrganization: string;
    /**
     * Descrição da subscription.
     * @type {string}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    description?: string | null;
    /**
     * Provedor da subscription.
     * @type {string}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    provider: CreateSubscriptionRequestBodyDtoProviderEnum;
    /**
     * Status da subscription.
     * @type {string}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    status: CreateSubscriptionRequestBodyDtoStatusEnum;
    /**
     * Data de expiração do trial.
     * @type {any}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    trialExpiresAt?: any | null;
    /**
     * Data inicial da primeira cobrança.
     * @type {any}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    initialDateOfFirstCharge?: any | null;
    /**
     * Preço mensal em centavos.
     * @type {number}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    montlyPriceInCents?: number | null;
    /**
     * Indica se há atraso no pagamento.
     * @type {boolean}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    latePayment?: boolean | null;
    /**
     * Data de corte do serviço.
     * @type {any}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    serviceCutoffDate?: any | null;
    /**
     * Histórico de status da subscription.
     * @type {Array<OrganizationEntityPopulatedSubscriptionStatusHistoryInner>}
     * @memberof CreateSubscriptionRequestBodyDto
     */
    statusHistory?: Array<OrganizationEntityPopulatedSubscriptionStatusHistoryInner>;
}


/**
 * @export
 */
export const CreateSubscriptionRequestBodyDtoProviderEnum = {
    Manual: 'MANUAL',
    AutomaticStripe: 'AUTOMATIC_STRIPE'
} as const;
export type CreateSubscriptionRequestBodyDtoProviderEnum = typeof CreateSubscriptionRequestBodyDtoProviderEnum[keyof typeof CreateSubscriptionRequestBodyDtoProviderEnum];

/**
 * @export
 */
export const CreateSubscriptionRequestBodyDtoStatusEnum = {
    Paying: 'PAYING',
    Trial: 'TRIAL',
    Free: 'FREE',
    Churned: 'CHURNED',
    NonConverted: 'NON_CONVERTED'
} as const;
export type CreateSubscriptionRequestBodyDtoStatusEnum = typeof CreateSubscriptionRequestBodyDtoStatusEnum[keyof typeof CreateSubscriptionRequestBodyDtoStatusEnum];


/**
 * Check if a given object implements the CreateSubscriptionRequestBodyDto interface.
 */
export function instanceOfCreateSubscriptionRequestBodyDto(value: object): value is CreateSubscriptionRequestBodyDto {
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateSubscriptionRequestBodyDtoFromJSON(json: any): CreateSubscriptionRequestBodyDto {
    return CreateSubscriptionRequestBodyDtoFromJSONTyped(json, false);
}

export function CreateSubscriptionRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ownerOrganization': json['ownerOrganization'],
        'description': json['description'] == null ? undefined : json['description'],
        'provider': json['provider'],
        'status': json['status'],
        'trialExpiresAt': json['trialExpiresAt'] == null ? undefined : json['trialExpiresAt'],
        'initialDateOfFirstCharge': json['initialDateOfFirstCharge'] == null ? undefined : json['initialDateOfFirstCharge'],
        'montlyPriceInCents': json['montlyPriceInCents'] == null ? undefined : json['montlyPriceInCents'],
        'latePayment': json['latePayment'] == null ? undefined : json['latePayment'],
        'serviceCutoffDate': json['serviceCutoffDate'] == null ? undefined : json['serviceCutoffDate'],
        'statusHistory': json['statusHistory'] == null ? undefined : ((json['statusHistory'] as Array<any>).map(OrganizationEntityPopulatedSubscriptionStatusHistoryInnerFromJSON)),
    };
}

export function CreateSubscriptionRequestBodyDtoToJSON(json: any): CreateSubscriptionRequestBodyDto {
    return CreateSubscriptionRequestBodyDtoToJSONTyped(json, false);
}

export function CreateSubscriptionRequestBodyDtoToJSONTyped(value?: CreateSubscriptionRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ownerOrganization': value['ownerOrganization'],
        'description': value['description'],
        'provider': value['provider'],
        'status': value['status'],
        'trialExpiresAt': value['trialExpiresAt'],
        'initialDateOfFirstCharge': value['initialDateOfFirstCharge'],
        'montlyPriceInCents': value['montlyPriceInCents'],
        'latePayment': value['latePayment'],
        'serviceCutoffDate': value['serviceCutoffDate'],
        'statusHistory': value['statusHistory'] == null ? undefined : ((value['statusHistory'] as Array<any>).map(OrganizationEntityPopulatedSubscriptionStatusHistoryInnerToJSON)),
    };
}

