/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Instituição financeira populada.
 * @export
 * @interface CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution
 */
export interface CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution {
    /**
     * Sofia identifier for the bank institution
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution
     */
    sofiaId: string;
    /**
     * Pluggy identifiers for the bank institution
     * @type {Array<string>}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution
     */
    pluggyIds: Array<string>;
    /**
     * Name of the bank institution
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution
     */
    name: string;
    /**
     * URL of the bank institution image
     * @type {string}
     * @memberof CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution
     */
    imageUrl: string;
}

/**
 * Check if a given object implements the CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution interface.
 */
export function instanceOfCreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution(value: object): value is CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution {
    if (!('sofiaId' in value) || value['sofiaId'] === undefined) return false;
    if (!('pluggyIds' in value) || value['pluggyIds'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionFromJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution {
    return CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionFromJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution {
    if (json == null) {
        return json;
    }
    return {
        
        'sofiaId': json['sofiaId'],
        'pluggyIds': json['pluggyIds'],
        'name': json['name'],
        'imageUrl': json['imageUrl'],
    };
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionToJSON(json: any): CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution {
    return CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionToJSONTyped(json, false);
}

export function CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitutionToJSONTyped(value?: CreateFinancialRecordRequestBodyDtoPopulatedAccountPopulatedInstitution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sofiaId': value['sofiaId'],
        'pluggyIds': value['pluggyIds'],
        'name': value['name'],
        'imageUrl': value['imageUrl'],
    };
}

