/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner } from './CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner';
import {
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerFromJSON,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerFromJSONTyped,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerToJSON,
    CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerToJSONTyped,
} from './CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner';

/**
 * Mensagem atual.
 * @export
 * @interface CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
 */
export interface CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage {
    /**
     * ID da mensagem.
     * @type {string}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
     */
    id: string;
    /**
     * Timestamp da mensagem.
     * @type {string}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
     */
    timestamp: string;
    /**
     * Email do remetente.
     * @type {string}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
     */
    email: string;
    /**
     * Nome do remetente.
     * @type {string}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
     */
    name?: string | null;
    /**
     * Conteúdo da mensagem.
     * @type {string}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
     */
    content?: string;
    /**
     * Arquivos anexados.
     * @type {Array<CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner>}
     * @memberof CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage
     */
    files?: Array<CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInner> | null;
}

/**
 * Check if a given object implements the CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage interface.
 */
export function instanceOfCreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage(value: object): value is CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessageFromJSON(json: any): CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage {
    return CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessageFromJSONTyped(json, false);
}

export function CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'content': json['content'] == null ? undefined : json['content'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerFromJSON)),
    };
}

export function CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessageToJSON(json: any): CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage {
    return CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessageToJSONTyped(json, false);
}

export function CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessageToJSONTyped(value?: CreateFinancialRecordRadarItemRequestBodyDtoEmailMessageDataCurrentMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'email': value['email'],
        'name': value['name'],
        'content': value['content'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(CreateFinancialRecordRadarItemRequestBodyDtoWhatsappMessageDataCurrentMessageFilesInnerToJSON)),
    };
}

