/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessExportResourceJobRequestBodyDtoRequester } from './ProcessExportResourceJobRequestBodyDtoRequester';
import {
    ProcessExportResourceJobRequestBodyDtoRequesterFromJSON,
    ProcessExportResourceJobRequestBodyDtoRequesterFromJSONTyped,
    ProcessExportResourceJobRequestBodyDtoRequesterToJSON,
    ProcessExportResourceJobRequestBodyDtoRequesterToJSONTyped,
} from './ProcessExportResourceJobRequestBodyDtoRequester';

/**
 * 
 * @export
 * @interface ExecuteBulkUpdateJobRequestBodyDto
 */
export interface ExecuteBulkUpdateJobRequestBodyDto {
    /**
     * 
     * @type {ProcessExportResourceJobRequestBodyDtoRequester}
     * @memberof ExecuteBulkUpdateJobRequestBodyDto
     */
    requester: ProcessExportResourceJobRequestBodyDtoRequester;
    /**
     * 
     * @type {string}
     * @memberof ExecuteBulkUpdateJobRequestBodyDto
     */
    bulkUpdateJobRequestId: string;
}

/**
 * Check if a given object implements the ExecuteBulkUpdateJobRequestBodyDto interface.
 */
export function instanceOfExecuteBulkUpdateJobRequestBodyDto(value: object): value is ExecuteBulkUpdateJobRequestBodyDto {
    if (!('requester' in value) || value['requester'] === undefined) return false;
    if (!('bulkUpdateJobRequestId' in value) || value['bulkUpdateJobRequestId'] === undefined) return false;
    return true;
}

export function ExecuteBulkUpdateJobRequestBodyDtoFromJSON(json: any): ExecuteBulkUpdateJobRequestBodyDto {
    return ExecuteBulkUpdateJobRequestBodyDtoFromJSONTyped(json, false);
}

export function ExecuteBulkUpdateJobRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteBulkUpdateJobRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requester': ProcessExportResourceJobRequestBodyDtoRequesterFromJSON(json['requester']),
        'bulkUpdateJobRequestId': json['bulkUpdateJobRequestId'],
    };
}

export function ExecuteBulkUpdateJobRequestBodyDtoToJSON(json: any): ExecuteBulkUpdateJobRequestBodyDto {
    return ExecuteBulkUpdateJobRequestBodyDtoToJSONTyped(json, false);
}

export function ExecuteBulkUpdateJobRequestBodyDtoToJSONTyped(value?: ExecuteBulkUpdateJobRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requester': ProcessExportResourceJobRequestBodyDtoRequesterToJSON(value['requester']),
        'bulkUpdateJobRequestId': value['bulkUpdateJobRequestId'],
    };
}

