/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportFinancialRecordsDto
 */
export interface ExportFinancialRecordsDto {
    /**
     * 
     * @type {string}
     * @memberof ExportFinancialRecordsDto
     */
    id: string;
}

/**
 * Check if a given object implements the ExportFinancialRecordsDto interface.
 */
export function instanceOfExportFinancialRecordsDto(value: object): value is ExportFinancialRecordsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ExportFinancialRecordsDtoFromJSON(json: any): ExportFinancialRecordsDto {
    return ExportFinancialRecordsDtoFromJSONTyped(json, false);
}

export function ExportFinancialRecordsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportFinancialRecordsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ExportFinancialRecordsDtoToJSON(json: any): ExportFinancialRecordsDto {
    return ExportFinancialRecordsDtoToJSONTyped(json, false);
}

export function ExportFinancialRecordsDtoToJSONTyped(value?: ExportFinancialRecordsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

