/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportBankAccountsDto
 */
export interface ExportBankAccountsDto {
    /**
     * 
     * @type {string}
     * @memberof ExportBankAccountsDto
     */
    id: string;
}

/**
 * Check if a given object implements the ExportBankAccountsDto interface.
 */
export function instanceOfExportBankAccountsDto(value: object): value is ExportBankAccountsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ExportBankAccountsDtoFromJSON(json: any): ExportBankAccountsDto {
    return ExportBankAccountsDtoFromJSONTyped(json, false);
}

export function ExportBankAccountsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportBankAccountsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ExportBankAccountsDtoToJSON(json: any): ExportBankAccountsDto {
    return ExportBankAccountsDtoToJSONTyped(json, false);
}

export function ExportBankAccountsDtoToJSONTyped(value?: ExportBankAccountsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

