/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactsPageDtoPageInfo } from './ContactsPageDtoPageInfo';
import {
    ContactsPageDtoPageInfoFromJSON,
    ContactsPageDtoPageInfoFromJSONTyped,
    ContactsPageDtoPageInfoToJSON,
    ContactsPageDtoPageInfoToJSONTyped,
} from './ContactsPageDtoPageInfo';
import type { FinancialRecordRadarItemsPageDtoItemsInner } from './FinancialRecordRadarItemsPageDtoItemsInner';
import {
    FinancialRecordRadarItemsPageDtoItemsInnerFromJSON,
    FinancialRecordRadarItemsPageDtoItemsInnerFromJSONTyped,
    FinancialRecordRadarItemsPageDtoItemsInnerToJSON,
    FinancialRecordRadarItemsPageDtoItemsInnerToJSONTyped,
} from './FinancialRecordRadarItemsPageDtoItemsInner';

/**
 * 
 * @export
 * @interface FinancialRecordRadarItemsPageDto
 */
export interface FinancialRecordRadarItemsPageDto {
    /**
     * 
     * @type {Array<FinancialRecordRadarItemsPageDtoItemsInner>}
     * @memberof FinancialRecordRadarItemsPageDto
     */
    items: Array<FinancialRecordRadarItemsPageDtoItemsInner>;
    /**
     * 
     * @type {ContactsPageDtoPageInfo}
     * @memberof FinancialRecordRadarItemsPageDto
     */
    pageInfo: ContactsPageDtoPageInfo;
}

/**
 * Check if a given object implements the FinancialRecordRadarItemsPageDto interface.
 */
export function instanceOfFinancialRecordRadarItemsPageDto(value: object): value is FinancialRecordRadarItemsPageDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageInfo' in value) || value['pageInfo'] === undefined) return false;
    return true;
}

export function FinancialRecordRadarItemsPageDtoFromJSON(json: any): FinancialRecordRadarItemsPageDto {
    return FinancialRecordRadarItemsPageDtoFromJSONTyped(json, false);
}

export function FinancialRecordRadarItemsPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialRecordRadarItemsPageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FinancialRecordRadarItemsPageDtoItemsInnerFromJSON)),
        'pageInfo': ContactsPageDtoPageInfoFromJSON(json['pageInfo']),
    };
}

export function FinancialRecordRadarItemsPageDtoToJSON(json: any): FinancialRecordRadarItemsPageDto {
    return FinancialRecordRadarItemsPageDtoToJSONTyped(json, false);
}

export function FinancialRecordRadarItemsPageDtoToJSONTyped(value?: FinancialRecordRadarItemsPageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(FinancialRecordRadarItemsPageDtoItemsInnerToJSON)),
        'pageInfo': ContactsPageDtoPageInfoToJSON(value['pageInfo']),
    };
}

