/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedFilesInner } from './CreateFinancialRecordRequestBodyDtoPopulatedFilesInner';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedFilesInner';
import type { CreateFinancialRecordRequestBodyDtoPopulatedAccount } from './CreateFinancialRecordRequestBodyDtoPopulatedAccount';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedAccountFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedAccountToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedAccount';
import type { CreateFinancialRecordRequestBodyDtoPopulatedTagsInner } from './CreateFinancialRecordRequestBodyDtoPopulatedTagsInner';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedTagsInner';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategory';
import type { CreateFinancialRecordRequestBodyDtoPopulatedContact } from './CreateFinancialRecordRequestBodyDtoPopulatedContact';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedContactToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedContactToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedContact';

/**
 * Registro financeiro atualizado pelo auto-execute.
 * @export
 * @interface FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
 */
export interface FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord {
    /**
     * Identificador do lançamento financeiro.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    id: string;
    /**
     * Identificador da organização dona do lançamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    ownerOrganization: string;
    /**
     * Direção do lançamento (entrada/saída).
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    direction: FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordDirectionEnum;
    /**
     * Data de vencimento.
     * @type {any}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    dueDate: any | null;
    /**
     * Variações da data de vencimento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    dueDateVariations?: string | null;
    /**
     * Identificador do contato relacionado.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    contact: string;
    /**
     * Descrição do lançamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    description: string;
    /**
     * Identificador da subcategoria.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    subcategory: string;
    /**
     * Valor do lançamento. É o valor em centavos. Exemplo: 10032 para R$ 100,32
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    amount: number;
    /**
     * Variações do valor do lançamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    amountVariations?: string | null;
    /**
     * Tags relacionadas.
     * @type {Array<string>}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    tags?: Array<string>;
    /**
     * Data de competência.
     * @type {any}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    competenceDate?: any | null;
    /**
     * Variações da data de competência.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    competenceDateVariations?: string | null;
    /**
     * Arquivos anexados.
     * @type {Array<string>}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    files?: Array<string>;
    /**
     * Ids de itens no radar relacionados.
     * @type {Array<string>}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    radarItems?: Array<string>;
    /**
     * Chave PIX.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    pixKey?: string | null;
    /**
     * Código do boleto.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    boletoCode?: string | null;
    /**
     * Código PIX para pagamento/recebimento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    pixCode?: string | null;
    /**
     * Número da nota fiscal.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    invoiceNumber?: string | null;
    /**
     * Indica se o lançamento foi concluído.
     * @type {boolean}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    completed?: boolean;
    /**
     * Data de pagamento.
     * @type {any}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    cashDate?: any | null;
    /**
     * Variações da data de pagamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    cashDateVariations?: string | null;
    /**
     * Identificador da conta.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    account?: string | null;
    /**
     * Valor do desconto. É o valor em centavos. Exemplo: 1000 para R$ 10,00
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    discount?: number | null;
    /**
     * Valor de multas e juros. É o valor em centavos. Exemplo: 1000 para R$ 10,00
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    finesAndInterest?: number | null;
    /**
     * Valor final do lançamento. É o valor em centavos. Exemplo: 10000 para R$ 100,00
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    finalAmount: number;
    /**
     * Variações do valor final do lançamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    finalAmountVariations?: string | null;
    /**
     * Dicas de busca com nomes de contatos para facilitar buscas textuais.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    contactHints?: string | null;
    /**
     * Dicas de busca com nomes de subcategorias/categorias para facilitar buscas textuais.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    subcategoryHints?: string | null;
    /**
     * Dicas de busca com nomes e números de contas bancárias para facilitar buscas textuais.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    bankAccountHints?: string | null;
    /**
     * Dicas de busca com nomes de tags para facilitar buscas textuais.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    tagsHints?: string | null;
    /**
     * Indica se foi reconciliado com uma transação bancária.
     * @type {boolean}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    reconciled?: boolean;
    /**
     * Identificador da transação bancária vinculada.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    bankTransaction?: string | null;
    /**
     * Identificador do lançamento financeiro parcelado.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    installmentFinancialRecord?: string | null;
    /**
     * Índice da parcela (1, 2, 3, etc.).
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    installmentNumber?: number | null;
    /**
     * Identificador do lançamento financeiro recorrente.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    recurringFinancialRecord?: string | null;
    /**
     * Data de criação do lançamento.
     * @type {any}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    createdAt?: any | null;
    /**
     * Data de atualização do lançamento.
     * @type {any}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    updatedAt?: any | null;
    /**
     * Arquivos anexados.
     * @type {Array<CreateFinancialRecordRequestBodyDtoPopulatedFilesInner>}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    populatedFiles?: Array<CreateFinancialRecordRequestBodyDtoPopulatedFilesInner>;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategory}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    populatedSubcategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategory | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedContact}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    populatedContact?: CreateFinancialRecordRequestBodyDtoPopulatedContact | null;
    /**
     * Tags relacionadas.
     * @type {Array<CreateFinancialRecordRequestBodyDtoPopulatedTagsInner>}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    populatedTags?: Array<CreateFinancialRecordRequestBodyDtoPopulatedTagsInner> | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedAccount}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    populatedAccount?: CreateFinancialRecordRequestBodyDtoPopulatedAccount | null;
    /**
     * Pontuação de busca do lançamento.
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    searchScore?: number | null;
    /**
     * Observações do lançamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    observations?: string | null;
    /**
     * Data de importação do lançamento.
     * @type {any}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    importedAt?: any | null;
    /**
     * Origem da importação do lançamento.
     * @type {string}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    importedBy?: string | null;
    /**
     * Índice global do lançamento financeiro no arquivo de importação.
     * @type {number}
     * @memberof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord
     */
    importGlobalIndex?: number | null;
}


/**
 * @export
 */
export const FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordDirectionEnum = typeof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordDirectionEnum[keyof typeof FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordDirectionEnum];


/**
 * Check if a given object implements the FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord interface.
 */
export function instanceOfFinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord(value: object): value is FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('finalAmount' in value) || value['finalAmount'] === undefined) return false;
    return true;
}

export function FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordFromJSON(json: any): FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord {
    return FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordFromJSONTyped(json, false);
}

export function FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'direction': json['direction'],
        'dueDate': json['dueDate'],
        'dueDateVariations': json['dueDateVariations'] == null ? undefined : json['dueDateVariations'],
        'contact': json['contact'],
        'description': json['description'],
        'subcategory': json['subcategory'],
        'amount': json['amount'],
        'amountVariations': json['amountVariations'] == null ? undefined : json['amountVariations'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'competenceDate': json['competenceDate'] == null ? undefined : json['competenceDate'],
        'competenceDateVariations': json['competenceDateVariations'] == null ? undefined : json['competenceDateVariations'],
        'files': json['files'] == null ? undefined : json['files'],
        'radarItems': json['radarItems'] == null ? undefined : json['radarItems'],
        'pixKey': json['pixKey'] == null ? undefined : json['pixKey'],
        'boletoCode': json['boletoCode'] == null ? undefined : json['boletoCode'],
        'pixCode': json['pixCode'] == null ? undefined : json['pixCode'],
        'invoiceNumber': json['invoiceNumber'] == null ? undefined : json['invoiceNumber'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'cashDate': json['cashDate'] == null ? undefined : json['cashDate'],
        'cashDateVariations': json['cashDateVariations'] == null ? undefined : json['cashDateVariations'],
        'account': json['account'] == null ? undefined : json['account'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'finesAndInterest': json['finesAndInterest'] == null ? undefined : json['finesAndInterest'],
        'finalAmount': json['finalAmount'],
        'finalAmountVariations': json['finalAmountVariations'] == null ? undefined : json['finalAmountVariations'],
        'contactHints': json['contactHints'] == null ? undefined : json['contactHints'],
        'subcategoryHints': json['subcategoryHints'] == null ? undefined : json['subcategoryHints'],
        'bankAccountHints': json['bankAccountHints'] == null ? undefined : json['bankAccountHints'],
        'tagsHints': json['tagsHints'] == null ? undefined : json['tagsHints'],
        'reconciled': json['reconciled'] == null ? undefined : json['reconciled'],
        'bankTransaction': json['bankTransaction'] == null ? undefined : json['bankTransaction'],
        'installmentFinancialRecord': json['installmentFinancialRecord'] == null ? undefined : json['installmentFinancialRecord'],
        'installmentNumber': json['installmentNumber'] == null ? undefined : json['installmentNumber'],
        'recurringFinancialRecord': json['recurringFinancialRecord'] == null ? undefined : json['recurringFinancialRecord'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'populatedFiles': json['populatedFiles'] == null ? undefined : ((json['populatedFiles'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSON)),
        'populatedSubcategory': json['populatedSubcategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON(json['populatedSubcategory']),
        'populatedContact': json['populatedContact'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSON(json['populatedContact']),
        'populatedTags': json['populatedTags'] == null ? undefined : ((json['populatedTags'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerFromJSON)),
        'populatedAccount': json['populatedAccount'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedAccountFromJSON(json['populatedAccount']),
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
        'observations': json['observations'] == null ? undefined : json['observations'],
        'importedAt': json['importedAt'] == null ? undefined : json['importedAt'],
        'importedBy': json['importedBy'] == null ? undefined : json['importedBy'],
        'importGlobalIndex': json['importGlobalIndex'] == null ? undefined : json['importGlobalIndex'],
    };
}

export function FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordToJSON(json: any): FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord {
    return FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordToJSONTyped(json, false);
}

export function FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecordToJSONTyped(value?: FinancialRecordRadarItemEntityAutoExecutePartialUpdatedFinancialRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'direction': value['direction'],
        'dueDate': value['dueDate'],
        'dueDateVariations': value['dueDateVariations'],
        'contact': value['contact'],
        'description': value['description'],
        'subcategory': value['subcategory'],
        'amount': value['amount'],
        'amountVariations': value['amountVariations'],
        'tags': value['tags'],
        'competenceDate': value['competenceDate'],
        'competenceDateVariations': value['competenceDateVariations'],
        'files': value['files'],
        'radarItems': value['radarItems'],
        'pixKey': value['pixKey'],
        'boletoCode': value['boletoCode'],
        'pixCode': value['pixCode'],
        'invoiceNumber': value['invoiceNumber'],
        'completed': value['completed'],
        'cashDate': value['cashDate'],
        'cashDateVariations': value['cashDateVariations'],
        'account': value['account'],
        'discount': value['discount'],
        'finesAndInterest': value['finesAndInterest'],
        'finalAmount': value['finalAmount'],
        'finalAmountVariations': value['finalAmountVariations'],
        'contactHints': value['contactHints'],
        'subcategoryHints': value['subcategoryHints'],
        'bankAccountHints': value['bankAccountHints'],
        'tagsHints': value['tagsHints'],
        'reconciled': value['reconciled'],
        'bankTransaction': value['bankTransaction'],
        'installmentFinancialRecord': value['installmentFinancialRecord'],
        'installmentNumber': value['installmentNumber'],
        'recurringFinancialRecord': value['recurringFinancialRecord'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'populatedFiles': value['populatedFiles'] == null ? undefined : ((value['populatedFiles'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSON)),
        'populatedSubcategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON(value['populatedSubcategory']),
        'populatedContact': CreateFinancialRecordRequestBodyDtoPopulatedContactToJSON(value['populatedContact']),
        'populatedTags': value['populatedTags'] == null ? undefined : ((value['populatedTags'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedTagsInnerToJSON)),
        'populatedAccount': CreateFinancialRecordRequestBodyDtoPopulatedAccountToJSON(value['populatedAccount']),
        'searchScore': value['searchScore'],
        'observations': value['observations'],
        'importedAt': value['importedAt'],
        'importedBy': value['importedBy'],
        'importGlobalIndex': value['importGlobalIndex'],
    };
}

