/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InboxRecordEntityLinksInner
 */
export interface InboxRecordEntityLinksInner {
    /**
     * Tipo do recurso vinculado.
     * @type {string}
     * @memberof InboxRecordEntityLinksInner
     */
    resourceType: InboxRecordEntityLinksInnerResourceTypeEnum;
    /**
     * ID do recurso vinculado.
     * @type {string}
     * @memberof InboxRecordEntityLinksInner
     */
    resourceId: string;
}


/**
 * @export
 */
export const InboxRecordEntityLinksInnerResourceTypeEnum = {
    FinancialRecord: 'FINANCIAL_RECORD'
} as const;
export type InboxRecordEntityLinksInnerResourceTypeEnum = typeof InboxRecordEntityLinksInnerResourceTypeEnum[keyof typeof InboxRecordEntityLinksInnerResourceTypeEnum];


/**
 * Check if a given object implements the InboxRecordEntityLinksInner interface.
 */
export function instanceOfInboxRecordEntityLinksInner(value: object): value is InboxRecordEntityLinksInner {
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('resourceId' in value) || value['resourceId'] === undefined) return false;
    return true;
}

export function InboxRecordEntityLinksInnerFromJSON(json: any): InboxRecordEntityLinksInner {
    return InboxRecordEntityLinksInnerFromJSONTyped(json, false);
}

export function InboxRecordEntityLinksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxRecordEntityLinksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceType': json['resourceType'],
        'resourceId': json['resourceId'],
    };
}

export function InboxRecordEntityLinksInnerToJSON(json: any): InboxRecordEntityLinksInner {
    return InboxRecordEntityLinksInnerToJSONTyped(json, false);
}

export function InboxRecordEntityLinksInnerToJSONTyped(value?: InboxRecordEntityLinksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceType': value['resourceType'],
        'resourceId': value['resourceId'],
    };
}

