/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessExportResourceJobRequestBodyDtoRequesterOrganization } from './ProcessExportResourceJobRequestBodyDtoRequesterOrganization';
import {
    ProcessExportResourceJobRequestBodyDtoRequesterOrganizationFromJSON,
    ProcessExportResourceJobRequestBodyDtoRequesterOrganizationFromJSONTyped,
    ProcessExportResourceJobRequestBodyDtoRequesterOrganizationToJSON,
    ProcessExportResourceJobRequestBodyDtoRequesterOrganizationToJSONTyped,
} from './ProcessExportResourceJobRequestBodyDtoRequesterOrganization';

/**
 * Usuário que solicitou a importação.
 * @export
 * @interface OfxImportJobRequestsPageDtoItemsInnerUser
 */
export interface OfxImportJobRequestsPageDtoItemsInnerUser {
    /**
     * 
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerUser
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerUser
     */
    primaryPhoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerUser
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerUser
     */
    lastName: string;
    /**
     * 
     * @type {ProcessExportResourceJobRequestBodyDtoRequesterOrganization}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerUser
     */
    organization?: ProcessExportResourceJobRequestBodyDtoRequesterOrganization | null;
}

/**
 * Check if a given object implements the OfxImportJobRequestsPageDtoItemsInnerUser interface.
 */
export function instanceOfOfxImportJobRequestsPageDtoItemsInnerUser(value: object): value is OfxImportJobRequestsPageDtoItemsInnerUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    if (!('primaryPhoneNumber' in value) || value['primaryPhoneNumber'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function OfxImportJobRequestsPageDtoItemsInnerUserFromJSON(json: any): OfxImportJobRequestsPageDtoItemsInnerUser {
    return OfxImportJobRequestsPageDtoItemsInnerUserFromJSONTyped(json, false);
}

export function OfxImportJobRequestsPageDtoItemsInnerUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfxImportJobRequestsPageDtoItemsInnerUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'primaryEmail': json['primaryEmail'],
        'primaryPhoneNumber': json['primaryPhoneNumber'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'organization': json['organization'] == null ? undefined : ProcessExportResourceJobRequestBodyDtoRequesterOrganizationFromJSON(json['organization']),
    };
}

export function OfxImportJobRequestsPageDtoItemsInnerUserToJSON(json: any): OfxImportJobRequestsPageDtoItemsInnerUser {
    return OfxImportJobRequestsPageDtoItemsInnerUserToJSONTyped(json, false);
}

export function OfxImportJobRequestsPageDtoItemsInnerUserToJSONTyped(value?: OfxImportJobRequestsPageDtoItemsInnerUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'primaryEmail': value['primaryEmail'],
        'primaryPhoneNumber': value['primaryPhoneNumber'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'organization': ProcessExportResourceJobRequestBodyDtoRequesterOrganizationToJSON(value['organization']),
    };
}

