/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
 */
export interface OfxImportJobRequestsPageDtoItemsInnerExecutionsInner {
    /**
     * Identificador da execução da importação OFX.
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    id: string;
    /**
     * Status da execução da importação OFX.
     * @type {string}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    status: OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerStatusEnum;
    /**
     * Número total de itens a serem processados.
     * @type {number}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    nTotalItems?: number | null;
    /**
     * Número de itens processados com sucesso.
     * @type {number}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    nSuccessItems?: number | null;
    /**
     * Número de itens que falharam ao processar.
     * @type {number}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    nFailedItems?: number | null;
    /**
     * Data de início da execução.
     * @type {any}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    startedAt?: any | null;
    /**
     * Data de término da execução.
     * @type {any}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    finishedAt?: any | null;
    /**
     * Data de criação da execução da importação OFX.
     * @type {any}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    createdAt: any | null;
    /**
     * Data de atualização da execução da importação OFX.
     * @type {any}
     * @memberof OfxImportJobRequestsPageDtoItemsInnerExecutionsInner
     */
    updatedAt: any | null;
}


/**
 * @export
 */
export const OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerStatusEnum = {
    Processing: 'PROCESSING',
    Finished: 'FINISHED'
} as const;
export type OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerStatusEnum = typeof OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerStatusEnum[keyof typeof OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerStatusEnum];


/**
 * Check if a given object implements the OfxImportJobRequestsPageDtoItemsInnerExecutionsInner interface.
 */
export function instanceOfOfxImportJobRequestsPageDtoItemsInnerExecutionsInner(value: object): value is OfxImportJobRequestsPageDtoItemsInnerExecutionsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerFromJSON(json: any): OfxImportJobRequestsPageDtoItemsInnerExecutionsInner {
    return OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerFromJSONTyped(json, false);
}

export function OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfxImportJobRequestsPageDtoItemsInnerExecutionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'nTotalItems': json['nTotalItems'] == null ? undefined : json['nTotalItems'],
        'nSuccessItems': json['nSuccessItems'] == null ? undefined : json['nSuccessItems'],
        'nFailedItems': json['nFailedItems'] == null ? undefined : json['nFailedItems'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'finishedAt': json['finishedAt'] == null ? undefined : json['finishedAt'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerToJSON(json: any): OfxImportJobRequestsPageDtoItemsInnerExecutionsInner {
    return OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerToJSONTyped(json, false);
}

export function OfxImportJobRequestsPageDtoItemsInnerExecutionsInnerToJSONTyped(value?: OfxImportJobRequestsPageDtoItemsInnerExecutionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'nTotalItems': value['nTotalItems'],
        'nSuccessItems': value['nSuccessItems'],
        'nFailedItems': value['nFailedItems'],
        'startedAt': value['startedAt'],
        'finishedAt': value['finishedAt'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

