/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 4.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationEntityPopulatedSubscriptionStatusHistoryInner } from './OrganizationEntityPopulatedSubscriptionStatusHistoryInner';
import {
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerFromJSON,
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerFromJSONTyped,
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerToJSON,
    OrganizationEntityPopulatedSubscriptionStatusHistoryInnerToJSONTyped,
} from './OrganizationEntityPopulatedSubscriptionStatusHistoryInner';

/**
 * Subscription populada.
 * @export
 * @interface OrganizationEntityPopulatedSubscription
 */
export interface OrganizationEntityPopulatedSubscription {
    /**
     * Identificador da subscription.
     * @type {string}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    id: string;
    /**
     * Identificador da organização dona da subscription.
     * @type {string}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    ownerOrganization: string;
    /**
     * Descrição da subscription.
     * @type {string}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    description?: string | null;
    /**
     * Provedor da subscription.
     * @type {string}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    provider: OrganizationEntityPopulatedSubscriptionProviderEnum;
    /**
     * Status da subscription.
     * @type {string}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    status: OrganizationEntityPopulatedSubscriptionStatusEnum;
    /**
     * Data de expiração do trial.
     * @type {any}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    trialExpiresAt?: any | null;
    /**
     * Data inicial da primeira cobrança.
     * @type {any}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    initialDateOfFirstCharge?: any | null;
    /**
     * Preço mensal em centavos.
     * @type {number}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    montlyPriceInCents?: number | null;
    /**
     * Indica se há atraso no pagamento.
     * @type {boolean}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    latePayment?: boolean | null;
    /**
     * Data de corte do serviço.
     * @type {any}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    serviceCutoffDate?: any | null;
    /**
     * Data de criação.
     * @type {any}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    createdAt: any | null;
    /**
     * Data de atualização.
     * @type {any}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    updatedAt: any | null;
    /**
     * Histórico de status da subscription.
     * @type {Array<OrganizationEntityPopulatedSubscriptionStatusHistoryInner>}
     * @memberof OrganizationEntityPopulatedSubscription
     */
    statusHistory?: Array<OrganizationEntityPopulatedSubscriptionStatusHistoryInner>;
}


/**
 * @export
 */
export const OrganizationEntityPopulatedSubscriptionProviderEnum = {
    Manual: 'MANUAL',
    AutomaticStripe: 'AUTOMATIC_STRIPE'
} as const;
export type OrganizationEntityPopulatedSubscriptionProviderEnum = typeof OrganizationEntityPopulatedSubscriptionProviderEnum[keyof typeof OrganizationEntityPopulatedSubscriptionProviderEnum];

/**
 * @export
 */
export const OrganizationEntityPopulatedSubscriptionStatusEnum = {
    Paying: 'PAYING',
    Trial: 'TRIAL',
    Free: 'FREE',
    Churned: 'CHURNED',
    NonConverted: 'NON_CONVERTED'
} as const;
export type OrganizationEntityPopulatedSubscriptionStatusEnum = typeof OrganizationEntityPopulatedSubscriptionStatusEnum[keyof typeof OrganizationEntityPopulatedSubscriptionStatusEnum];


/**
 * Check if a given object implements the OrganizationEntityPopulatedSubscription interface.
 */
export function instanceOfOrganizationEntityPopulatedSubscription(value: object): value is OrganizationEntityPopulatedSubscription {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizationEntityPopulatedSubscriptionFromJSON(json: any): OrganizationEntityPopulatedSubscription {
    return OrganizationEntityPopulatedSubscriptionFromJSONTyped(json, false);
}

export function OrganizationEntityPopulatedSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationEntityPopulatedSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'description': json['description'] == null ? undefined : json['description'],
        'provider': json['provider'],
        'status': json['status'],
        'trialExpiresAt': json['trialExpiresAt'] == null ? undefined : json['trialExpiresAt'],
        'initialDateOfFirstCharge': json['initialDateOfFirstCharge'] == null ? undefined : json['initialDateOfFirstCharge'],
        'montlyPriceInCents': json['montlyPriceInCents'] == null ? undefined : json['montlyPriceInCents'],
        'latePayment': json['latePayment'] == null ? undefined : json['latePayment'],
        'serviceCutoffDate': json['serviceCutoffDate'] == null ? undefined : json['serviceCutoffDate'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'statusHistory': json['statusHistory'] == null ? undefined : ((json['statusHistory'] as Array<any>).map(OrganizationEntityPopulatedSubscriptionStatusHistoryInnerFromJSON)),
    };
}

export function OrganizationEntityPopulatedSubscriptionToJSON(json: any): OrganizationEntityPopulatedSubscription {
    return OrganizationEntityPopulatedSubscriptionToJSONTyped(json, false);
}

export function OrganizationEntityPopulatedSubscriptionToJSONTyped(value?: OrganizationEntityPopulatedSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'description': value['description'],
        'provider': value['provider'],
        'status': value['status'],
        'trialExpiresAt': value['trialExpiresAt'],
        'initialDateOfFirstCharge': value['initialDateOfFirstCharge'],
        'montlyPriceInCents': value['montlyPriceInCents'],
        'latePayment': value['latePayment'],
        'serviceCutoffDate': value['serviceCutoffDate'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'statusHistory': value['statusHistory'] == null ? undefined : ((value['statusHistory'] as Array<any>).map(OrganizationEntityPopulatedSubscriptionStatusHistoryInnerToJSON)),
    };
}

