/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategory } from './NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategory';
import {
    NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategoryFromJSON,
    NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategoryFromJSONTyped,
    NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategoryToJSON,
    NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategoryToJSONTyped,
} from './NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategory';
import type { ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategory } from './ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategory';
import {
    ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategoryFromJSON,
    ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategoryFromJSONTyped,
    ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategoryToJSON,
    ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategoryToJSONTyped,
} from './ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategory';

/**
 * 
 * @export
 * @interface PartialUpdateSubcategoryRequestBodyDto
 */
export interface PartialUpdateSubcategoryRequestBodyDto {
    /**
     * Nome da subcategoria.
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    name?: string;
    /**
     * Slug da subcategoria.
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    slug?: string;
    /**
     * Índice da subcategoria.
     * @type {number}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    category?: string;
    /**
     * 
     * @type {NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategory}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    populatedCategory?: NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategory | null;
    /**
     * 
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    normalizedSubcategory?: string | null;
    /**
     * 
     * @type {ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategory}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    populatedNormalizedSubcategory?: ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategory | null;
    /**
     * Canal de origem da operação
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    channel: PartialUpdateSubcategoryRequestBodyDtoChannelEnum;
}


/**
 * @export
 */
export const PartialUpdateSubcategoryRequestBodyDtoChannelEnum = {
    WebApp: 'WEB_APP',
    Whatsapp: 'WHATSAPP',
    System: 'SYSTEM'
} as const;
export type PartialUpdateSubcategoryRequestBodyDtoChannelEnum = typeof PartialUpdateSubcategoryRequestBodyDtoChannelEnum[keyof typeof PartialUpdateSubcategoryRequestBodyDtoChannelEnum];


/**
 * Check if a given object implements the PartialUpdateSubcategoryRequestBodyDto interface.
 */
export function instanceOfPartialUpdateSubcategoryRequestBodyDto(value: object): value is PartialUpdateSubcategoryRequestBodyDto {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    return true;
}

export function PartialUpdateSubcategoryRequestBodyDtoFromJSON(json: any): PartialUpdateSubcategoryRequestBodyDto {
    return PartialUpdateSubcategoryRequestBodyDtoFromJSONTyped(json, false);
}

export function PartialUpdateSubcategoryRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialUpdateSubcategoryRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'index': json['index'] == null ? undefined : json['index'],
        'category': json['category'] == null ? undefined : json['category'],
        'populatedCategory': json['populatedCategory'] == null ? undefined : NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategoryFromJSON(json['populatedCategory']),
        'normalizedSubcategory': json['normalizedSubcategory'] == null ? undefined : json['normalizedSubcategory'],
        'populatedNormalizedSubcategory': json['populatedNormalizedSubcategory'] == null ? undefined : ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategoryFromJSON(json['populatedNormalizedSubcategory']),
        'channel': json['channel'],
    };
}

export function PartialUpdateSubcategoryRequestBodyDtoToJSON(json: any): PartialUpdateSubcategoryRequestBodyDto {
    return PartialUpdateSubcategoryRequestBodyDtoToJSONTyped(json, false);
}

export function PartialUpdateSubcategoryRequestBodyDtoToJSONTyped(value?: PartialUpdateSubcategoryRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'index': value['index'],
        'category': value['category'],
        'populatedCategory': NormalizedSubcategoriesPageEntityItemsInnerPopulatedCategoryToJSON(value['populatedCategory']),
        'normalizedSubcategory': value['normalizedSubcategory'],
        'populatedNormalizedSubcategory': ExternalCreateSubcategoryRequestBodyDtoPopulatedNormalizedSubcategoryToJSON(value['populatedNormalizedSubcategory']),
        'channel': value['channel'],
    };
}

