/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartialUpdateBankAccountRequestBodyDto
 */
export interface PartialUpdateBankAccountRequestBodyDto {
    /**
     * Nome da conta bancária.
     * @type {string}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    name?: string;
    /**
     * Número da conta ou cartão.
     * @type {string}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    number?: string;
    /**
     * Indica se a conta é a padrão.
     * @type {boolean}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    isDefault?: boolean;
    /**
     * Data do saldo inicial.
     * @type {any}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    initialBalanceDate?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    initialBalanceAmount?: string | null;
    /**
     * Instituição financeira.
     * @type {string}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    institution?: string;
    /**
     * Indica se a conta está ativa.
     * @type {boolean}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    active?: boolean;
    /**
     * Canal de origem da operação
     * @type {string}
     * @memberof PartialUpdateBankAccountRequestBodyDto
     */
    channel: PartialUpdateBankAccountRequestBodyDtoChannelEnum;
}


/**
 * @export
 */
export const PartialUpdateBankAccountRequestBodyDtoChannelEnum = {
    WebApp: 'WEB_APP',
    Whatsapp: 'WHATSAPP',
    System: 'SYSTEM'
} as const;
export type PartialUpdateBankAccountRequestBodyDtoChannelEnum = typeof PartialUpdateBankAccountRequestBodyDtoChannelEnum[keyof typeof PartialUpdateBankAccountRequestBodyDtoChannelEnum];


/**
 * Check if a given object implements the PartialUpdateBankAccountRequestBodyDto interface.
 */
export function instanceOfPartialUpdateBankAccountRequestBodyDto(value: object): value is PartialUpdateBankAccountRequestBodyDto {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    return true;
}

export function PartialUpdateBankAccountRequestBodyDtoFromJSON(json: any): PartialUpdateBankAccountRequestBodyDto {
    return PartialUpdateBankAccountRequestBodyDtoFromJSONTyped(json, false);
}

export function PartialUpdateBankAccountRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialUpdateBankAccountRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'number': json['number'] == null ? undefined : json['number'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'initialBalanceDate': json['initialBalanceDate'] == null ? undefined : json['initialBalanceDate'],
        'initialBalanceAmount': json['initialBalanceAmount'] == null ? undefined : json['initialBalanceAmount'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'active': json['active'] == null ? undefined : json['active'],
        'channel': json['channel'],
    };
}

export function PartialUpdateBankAccountRequestBodyDtoToJSON(json: any): PartialUpdateBankAccountRequestBodyDto {
    return PartialUpdateBankAccountRequestBodyDtoToJSONTyped(json, false);
}

export function PartialUpdateBankAccountRequestBodyDtoToJSONTyped(value?: PartialUpdateBankAccountRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'number': value['number'],
        'isDefault': value['isDefault'],
        'initialBalanceDate': value['initialBalanceDate'],
        'initialBalanceAmount': value['initialBalanceAmount'],
        'institution': value['institution'],
        'active': value['active'],
        'channel': value['channel'],
    };
}

