/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartialUpdateCustomerRequestBodyDto
 */
export interface PartialUpdateCustomerRequestBodyDto {
    /**
     * Nome do customer.
     * @type {string}
     * @memberof PartialUpdateCustomerRequestBodyDto
     */
    name?: string;
    /**
     * Descrição do customer.
     * @type {string}
     * @memberof PartialUpdateCustomerRequestBodyDto
     */
    description?: string | null;
    /**
     * Tipo do customer.
     * @type {string}
     * @memberof PartialUpdateCustomerRequestBodyDto
     */
    type?: PartialUpdateCustomerRequestBodyDtoTypeEnum;
    /**
     * Identificadores das organizações filhas (clerkId).
     * @type {Array<string>}
     * @memberof PartialUpdateCustomerRequestBodyDto
     */
    childrenOrganizationsClerkIds?: Array<string>;
    /**
     * Data inicial do customer.
     * @type {any}
     * @memberof PartialUpdateCustomerRequestBodyDto
     */
    initialDate?: any | null;
}


/**
 * @export
 */
export const PartialUpdateCustomerRequestBodyDtoTypeEnum = {
    BpoOffice: 'BPO_OFFICE',
    Company: 'COMPANY'
} as const;
export type PartialUpdateCustomerRequestBodyDtoTypeEnum = typeof PartialUpdateCustomerRequestBodyDtoTypeEnum[keyof typeof PartialUpdateCustomerRequestBodyDtoTypeEnum];


/**
 * Check if a given object implements the PartialUpdateCustomerRequestBodyDto interface.
 */
export function instanceOfPartialUpdateCustomerRequestBodyDto(value: object): value is PartialUpdateCustomerRequestBodyDto {
    return true;
}

export function PartialUpdateCustomerRequestBodyDtoFromJSON(json: any): PartialUpdateCustomerRequestBodyDto {
    return PartialUpdateCustomerRequestBodyDtoFromJSONTyped(json, false);
}

export function PartialUpdateCustomerRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialUpdateCustomerRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'childrenOrganizationsClerkIds': json['childrenOrganizationsClerkIds'] == null ? undefined : json['childrenOrganizationsClerkIds'],
        'initialDate': json['initialDate'] == null ? undefined : json['initialDate'],
    };
}

export function PartialUpdateCustomerRequestBodyDtoToJSON(json: any): PartialUpdateCustomerRequestBodyDto {
    return PartialUpdateCustomerRequestBodyDtoToJSONTyped(json, false);
}

export function PartialUpdateCustomerRequestBodyDtoToJSONTyped(value?: PartialUpdateCustomerRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'childrenOrganizationsClerkIds': value['childrenOrganizationsClerkIds'],
        'initialDate': value['initialDate'],
    };
}

