/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory';

/**
 * 
 * @export
 * @interface PartialUpdateSubcategoryRequestBodyDto
 */
export interface PartialUpdateSubcategoryRequestBodyDto {
    /**
     * Nome da subcategoria.
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    name?: string;
    /**
     * Slug da subcategoria.
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    slug?: string;
    /**
     * Índice da subcategoria.
     * @type {number}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    category?: string;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    populatedCategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory | null;
    /**
     * 
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    normalizedSubcategory?: string | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    populatedNormalizedSubcategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory | null;
    /**
     * Indica se a subcategoria deve ser exibida no DRE.
     * @type {boolean}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    considerInDre?: boolean;
    /**
     * Indica se a subcategoria representa uma transferência interna.
     * @type {boolean}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    isInternalTransfer?: boolean;
    /**
     * Descrição da subcategoria.
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    description?: string;
    /**
     * Indica se a subcategoria está ativa.
     * @type {boolean}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    active?: boolean;
    /**
     * Pontuação de busca da subcategoria.
     * @type {number}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    searchScore?: number | null;
    /**
     * Data de importação da subcategoria.
     * @type {any}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    importedAt?: any | null;
    /**
     * Origem da importação da subcategoria.
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    importedBy?: string | null;
    /**
     * Canal de origem da operação
     * @type {string}
     * @memberof PartialUpdateSubcategoryRequestBodyDto
     */
    channel: PartialUpdateSubcategoryRequestBodyDtoChannelEnum;
}


/**
 * @export
 */
export const PartialUpdateSubcategoryRequestBodyDtoChannelEnum = {
    WebApp: 'WEB_APP',
    Whatsapp: 'WHATSAPP',
    System: 'SYSTEM',
    Email: 'EMAIL'
} as const;
export type PartialUpdateSubcategoryRequestBodyDtoChannelEnum = typeof PartialUpdateSubcategoryRequestBodyDtoChannelEnum[keyof typeof PartialUpdateSubcategoryRequestBodyDtoChannelEnum];


/**
 * Check if a given object implements the PartialUpdateSubcategoryRequestBodyDto interface.
 */
export function instanceOfPartialUpdateSubcategoryRequestBodyDto(value: object): value is PartialUpdateSubcategoryRequestBodyDto {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    return true;
}

export function PartialUpdateSubcategoryRequestBodyDtoFromJSON(json: any): PartialUpdateSubcategoryRequestBodyDto {
    return PartialUpdateSubcategoryRequestBodyDtoFromJSONTyped(json, false);
}

export function PartialUpdateSubcategoryRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialUpdateSubcategoryRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'index': json['index'] == null ? undefined : json['index'],
        'category': json['category'] == null ? undefined : json['category'],
        'populatedCategory': json['populatedCategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON(json['populatedCategory']),
        'normalizedSubcategory': json['normalizedSubcategory'] == null ? undefined : json['normalizedSubcategory'],
        'populatedNormalizedSubcategory': json['populatedNormalizedSubcategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSON(json['populatedNormalizedSubcategory']),
        'considerInDre': json['considerInDre'] == null ? undefined : json['considerInDre'],
        'isInternalTransfer': json['isInternalTransfer'] == null ? undefined : json['isInternalTransfer'],
        'description': json['description'] == null ? undefined : json['description'],
        'active': json['active'] == null ? undefined : json['active'],
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
        'importedAt': json['importedAt'] == null ? undefined : json['importedAt'],
        'importedBy': json['importedBy'] == null ? undefined : json['importedBy'],
        'channel': json['channel'],
    };
}

export function PartialUpdateSubcategoryRequestBodyDtoToJSON(json: any): PartialUpdateSubcategoryRequestBodyDto {
    return PartialUpdateSubcategoryRequestBodyDtoToJSONTyped(json, false);
}

export function PartialUpdateSubcategoryRequestBodyDtoToJSONTyped(value?: PartialUpdateSubcategoryRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'index': value['index'],
        'category': value['category'],
        'populatedCategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON(value['populatedCategory']),
        'normalizedSubcategory': value['normalizedSubcategory'],
        'populatedNormalizedSubcategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSON(value['populatedNormalizedSubcategory']),
        'considerInDre': value['considerInDre'],
        'isInternalTransfer': value['isInternalTransfer'],
        'description': value['description'],
        'active': value['active'],
        'searchScore': value['searchScore'],
        'importedAt': value['importedAt'],
        'importedBy': value['importedBy'],
        'channel': value['channel'],
    };
}

