/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostsPageEntityItemsInner } from './PostsPageEntityItemsInner';
import {
    PostsPageEntityItemsInnerFromJSON,
    PostsPageEntityItemsInnerFromJSONTyped,
    PostsPageEntityItemsInnerToJSON,
    PostsPageEntityItemsInnerToJSONTyped,
} from './PostsPageEntityItemsInner';
import type { ContactsPageEntityPageInfo } from './ContactsPageEntityPageInfo';
import {
    ContactsPageEntityPageInfoFromJSON,
    ContactsPageEntityPageInfoFromJSONTyped,
    ContactsPageEntityPageInfoToJSON,
    ContactsPageEntityPageInfoToJSONTyped,
} from './ContactsPageEntityPageInfo';

/**
 * 
 * @export
 * @interface PostsPageEntity
 */
export interface PostsPageEntity {
    /**
     * 
     * @type {Array<PostsPageEntityItemsInner>}
     * @memberof PostsPageEntity
     */
    items: Array<PostsPageEntityItemsInner>;
    /**
     * 
     * @type {ContactsPageEntityPageInfo}
     * @memberof PostsPageEntity
     */
    pageInfo: ContactsPageEntityPageInfo;
}

/**
 * Check if a given object implements the PostsPageEntity interface.
 */
export function instanceOfPostsPageEntity(value: object): value is PostsPageEntity {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageInfo' in value) || value['pageInfo'] === undefined) return false;
    return true;
}

export function PostsPageEntityFromJSON(json: any): PostsPageEntity {
    return PostsPageEntityFromJSONTyped(json, false);
}

export function PostsPageEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsPageEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PostsPageEntityItemsInnerFromJSON)),
        'pageInfo': ContactsPageEntityPageInfoFromJSON(json['pageInfo']),
    };
}

export function PostsPageEntityToJSON(json: any): PostsPageEntity {
    return PostsPageEntityToJSONTyped(json, false);
}

export function PostsPageEntityToJSONTyped(value?: PostsPageEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PostsPageEntityItemsInnerToJSON)),
        'pageInfo': ContactsPageEntityPageInfoToJSON(value['pageInfo']),
    };
}

