/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tag do post.
 * @export
 * @interface PostEntityTagsInnerOneOf
 */
export interface PostEntityTagsInnerOneOf {
    /**
     * Identificador da tag.
     * @type {string}
     * @memberof PostEntityTagsInnerOneOf
     */
    id: string;
    /**
     * Identificador da organização.
     * @type {string}
     * @memberof PostEntityTagsInnerOneOf
     */
    organization: string;
    /**
     * Identificador do usuário que criou a tag.
     * @type {string}
     * @memberof PostEntityTagsInnerOneOf
     */
    createdByUser: string;
    /**
     * Nome da tag.
     * @type {string}
     * @memberof PostEntityTagsInnerOneOf
     */
    name: string;
    /**
     * Data de criação da tag.
     * @type {Date}
     * @memberof PostEntityTagsInnerOneOf
     */
    createdAt: Date;
    /**
     * Data de atualização da tag.
     * @type {Date}
     * @memberof PostEntityTagsInnerOneOf
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PostEntityTagsInnerOneOf interface.
 */
export function instanceOfPostEntityTagsInnerOneOf(value: object): value is PostEntityTagsInnerOneOf {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('createdByUser' in value) || value['createdByUser'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PostEntityTagsInnerOneOfFromJSON(json: any): PostEntityTagsInnerOneOf {
    return PostEntityTagsInnerOneOfFromJSONTyped(json, false);
}

export function PostEntityTagsInnerOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostEntityTagsInnerOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization': json['organization'],
        'createdByUser': json['createdByUser'],
        'name': json['name'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PostEntityTagsInnerOneOfToJSON(json: any): PostEntityTagsInnerOneOf {
    return PostEntityTagsInnerOneOfToJSONTyped(json, false);
}

export function PostEntityTagsInnerOneOfToJSONTyped(value?: PostEntityTagsInnerOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization': value['organization'],
        'createdByUser': value['createdByUser'],
        'name': value['name'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

