/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent
 */
export interface ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent {
    /**
     * 
     * @type {string}
     * @memberof ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent
     */
    sharedContacts: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent
     */
    sharedSubcategories: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent
     */
    sharedTags: boolean;
}

/**
 * Check if a given object implements the ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent interface.
 */
export function instanceOfProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent(value: object): value is ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sharedContacts' in value) || value['sharedContacts'] === undefined) return false;
    if (!('sharedSubcategories' in value) || value['sharedSubcategories'] === undefined) return false;
    if (!('sharedTags' in value) || value['sharedTags'] === undefined) return false;
    return true;
}

export function ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParentFromJSON(json: any): ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent {
    return ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParentFromJSONTyped(json, false);
}

export function ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sharedContacts': json['sharedContacts'],
        'sharedSubcategories': json['sharedSubcategories'],
        'sharedTags': json['sharedTags'],
    };
}

export function ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParentToJSON(json: any): ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent {
    return ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParentToJSONTyped(json, false);
}

export function ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParentToJSONTyped(value?: ProcessExportResourceJobRequestBodyDtoRequesterOrganizationParent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'sharedContacts': value['sharedContacts'],
        'sharedSubcategories': value['sharedSubcategories'],
        'sharedTags': value['sharedTags'],
    };
}

