/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessExportResourceJobRequestBodyDtoRequester } from './ProcessExportResourceJobRequestBodyDtoRequester';
import {
    ProcessExportResourceJobRequestBodyDtoRequesterFromJSON,
    ProcessExportResourceJobRequestBodyDtoRequesterFromJSONTyped,
    ProcessExportResourceJobRequestBodyDtoRequesterToJSON,
    ProcessExportResourceJobRequestBodyDtoRequesterToJSONTyped,
} from './ProcessExportResourceJobRequestBodyDtoRequester';

/**
 * 
 * @export
 * @interface ProcessExportResourceJobRequestBodyDto
 */
export interface ProcessExportResourceJobRequestBodyDto {
    /**
     * 
     * @type {string}
     * @memberof ProcessExportResourceJobRequestBodyDto
     */
    exportResourceJobRequestId: string;
    /**
     * 
     * @type {ProcessExportResourceJobRequestBodyDtoRequester}
     * @memberof ProcessExportResourceJobRequestBodyDto
     */
    requester: ProcessExportResourceJobRequestBodyDtoRequester;
}

/**
 * Check if a given object implements the ProcessExportResourceJobRequestBodyDto interface.
 */
export function instanceOfProcessExportResourceJobRequestBodyDto(value: object): value is ProcessExportResourceJobRequestBodyDto {
    if (!('exportResourceJobRequestId' in value) || value['exportResourceJobRequestId'] === undefined) return false;
    if (!('requester' in value) || value['requester'] === undefined) return false;
    return true;
}

export function ProcessExportResourceJobRequestBodyDtoFromJSON(json: any): ProcessExportResourceJobRequestBodyDto {
    return ProcessExportResourceJobRequestBodyDtoFromJSONTyped(json, false);
}

export function ProcessExportResourceJobRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessExportResourceJobRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'exportResourceJobRequestId': json['exportResourceJobRequestId'],
        'requester': ProcessExportResourceJobRequestBodyDtoRequesterFromJSON(json['requester']),
    };
}

export function ProcessExportResourceJobRequestBodyDtoToJSON(json: any): ProcessExportResourceJobRequestBodyDto {
    return ProcessExportResourceJobRequestBodyDtoToJSONTyped(json, false);
}

export function ProcessExportResourceJobRequestBodyDtoToJSONTyped(value?: ProcessExportResourceJobRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exportResourceJobRequestId': value['exportResourceJobRequestId'],
        'requester': ProcessExportResourceJobRequestBodyDtoRequesterToJSON(value['requester']),
    };
}

