/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryResponseDto
 */
export interface QueryResponseDto {
    /**
     * Identificador único da consulta.
     * @type {string}
     * @memberof QueryResponseDto
     */
    id: string;
    /**
     * Identificador da organização dona da consulta.
     * @type {string}
     * @memberof QueryResponseDto
     */
    ownerOrganization: string;
    /**
     * Dados da consulta como um objeto de chave-valor.
     * @type {{ [key: string]: string; }}
     * @memberof QueryResponseDto
     */
    data: { [key: string]: string; };
    /**
     * Data de criação da consulta.
     * @type {any}
     * @memberof QueryResponseDto
     */
    createdAt: any | null;
    /**
     * Data de atualização da consulta.
     * @type {any}
     * @memberof QueryResponseDto
     */
    updatedAt: any | null;
}

/**
 * Check if a given object implements the QueryResponseDto interface.
 */
export function instanceOfQueryResponseDto(value: object): value is QueryResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function QueryResponseDtoFromJSON(json: any): QueryResponseDto {
    return QueryResponseDtoFromJSONTyped(json, false);
}

export function QueryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'data': json['data'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function QueryResponseDtoToJSON(json: any): QueryResponseDto {
    return QueryResponseDtoToJSONTyped(json, false);
}

export function QueryResponseDtoToJSONTyped(value?: QueryResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'data': value['data'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

