/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReconcileBankTransactionRequestBodyDto
 */
export interface ReconcileBankTransactionRequestBodyDto {
    /**
     * Lista de IDs dos lançamentos financeiros a serem vinculados.
     * @type {Array<string>}
     * @memberof ReconcileBankTransactionRequestBodyDto
     */
    financialRecordIds: Array<string>;
}

/**
 * Check if a given object implements the ReconcileBankTransactionRequestBodyDto interface.
 */
export function instanceOfReconcileBankTransactionRequestBodyDto(value: object): value is ReconcileBankTransactionRequestBodyDto {
    if (!('financialRecordIds' in value) || value['financialRecordIds'] === undefined) return false;
    return true;
}

export function ReconcileBankTransactionRequestBodyDtoFromJSON(json: any): ReconcileBankTransactionRequestBodyDto {
    return ReconcileBankTransactionRequestBodyDtoFromJSONTyped(json, false);
}

export function ReconcileBankTransactionRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReconcileBankTransactionRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'financialRecordIds': json['financialRecordIds'],
    };
}

export function ReconcileBankTransactionRequestBodyDtoToJSON(json: any): ReconcileBankTransactionRequestBodyDto {
    return ReconcileBankTransactionRequestBodyDtoToJSONTyped(json, false);
}

export function ReconcileBankTransactionRequestBodyDtoToJSONTyped(value?: ReconcileBankTransactionRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'financialRecordIds': value['financialRecordIds'],
    };
}

