/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedFilesInner } from './CreateFinancialRecordRequestBodyDtoPopulatedFilesInner';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedFilesInner';
import type { CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory } from './CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory';
import {
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON,
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSONTyped,
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON,
    CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSONTyped,
} from './CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory';
import type { CreateFinancialRecordRequestBodyDtoPopulatedContact } from './CreateFinancialRecordRequestBodyDtoPopulatedContact';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedContactToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedContactToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedContact';
import type { TagsPageEntityItemsInner } from './TagsPageEntityItemsInner';
import {
    TagsPageEntityItemsInnerFromJSON,
    TagsPageEntityItemsInnerFromJSONTyped,
    TagsPageEntityItemsInnerToJSON,
    TagsPageEntityItemsInnerToJSONTyped,
} from './TagsPageEntityItemsInner';

/**
 * 
 * @export
 * @interface RecurringFinancialRecordEntity
 */
export interface RecurringFinancialRecordEntity {
    /**
     * Identificador do lançamento financeiro recorrente.
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    id: string;
    /**
     * Identificador da organização dona do lançamento.
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    ownerOrganization: string;
    /**
     * Direção do lançamento (entrada/saída).
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    direction: RecurringFinancialRecordEntityDirectionEnum;
    /**
     * Data da primeira ocorrência.
     * @type {any}
     * @memberof RecurringFinancialRecordEntity
     */
    firstOccurrenceDate: any | null;
    /**
     * Descrição do lançamento.
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    description: string;
    /**
     * Identificador do contato relacionado.
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    contact: string;
    /**
     * Identificador da subcategoria.
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    subcategory: string;
    /**
     * Valor do lançamento.
     * @type {number}
     * @memberof RecurringFinancialRecordEntity
     */
    amount: number;
    /**
     * Tags relacionadas.
     * @type {Array<string>}
     * @memberof RecurringFinancialRecordEntity
     */
    tags?: Array<string>;
    /**
     * Arquivos anexados.
     * @type {Array<string>}
     * @memberof RecurringFinancialRecordEntity
     */
    files?: Array<string>;
    /**
     * Frequência de repetição do lançamento.
     * @type {string}
     * @memberof RecurringFinancialRecordEntity
     */
    frequency: RecurringFinancialRecordEntityFrequencyEnum;
    /**
     * Dia de repetição do lançamento.
     * @type {number}
     * @memberof RecurringFinancialRecordEntity
     */
    repetitionDay: number;
    /**
     * Mês de repetição do lançamento.
     * @type {number}
     * @memberof RecurringFinancialRecordEntity
     */
    repetitionMonth?: number;
    /**
     * Indica se o lançamento será apenas em dias úteis.
     * @type {boolean}
     * @memberof RecurringFinancialRecordEntity
     */
    onlyBusinessDays?: boolean;
    /**
     * Indica se o lançamento será completado automaticamente.
     * @type {boolean}
     * @memberof RecurringFinancialRecordEntity
     */
    automaticCompletion?: boolean;
    /**
     * Indica se o lançamento recorrente está ativo.
     * @type {boolean}
     * @memberof RecurringFinancialRecordEntity
     */
    isActive?: boolean;
    /**
     * Data de criação do lançamento.
     * @type {any}
     * @memberof RecurringFinancialRecordEntity
     */
    createdAt?: any | null;
    /**
     * Data de atualização do lançamento.
     * @type {any}
     * @memberof RecurringFinancialRecordEntity
     */
    updatedAt?: any | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedContact}
     * @memberof RecurringFinancialRecordEntity
     */
    populatedContact?: CreateFinancialRecordRequestBodyDtoPopulatedContact | null;
    /**
     * Tags relacionadas.
     * @type {Array<TagsPageEntityItemsInner>}
     * @memberof RecurringFinancialRecordEntity
     */
    populatedTags?: Array<TagsPageEntityItemsInner> | null;
    /**
     * 
     * @type {CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory}
     * @memberof RecurringFinancialRecordEntity
     */
    populatedSubcategory?: CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategory | null;
    /**
     * Arquivos anexados.
     * @type {Array<CreateFinancialRecordRequestBodyDtoPopulatedFilesInner>}
     * @memberof RecurringFinancialRecordEntity
     */
    populatedFiles?: Array<CreateFinancialRecordRequestBodyDtoPopulatedFilesInner> | null;
}


/**
 * @export
 */
export const RecurringFinancialRecordEntityDirectionEnum = {
    Income: 'INCOME',
    Outcome: 'OUTCOME'
} as const;
export type RecurringFinancialRecordEntityDirectionEnum = typeof RecurringFinancialRecordEntityDirectionEnum[keyof typeof RecurringFinancialRecordEntityDirectionEnum];

/**
 * @export
 */
export const RecurringFinancialRecordEntityFrequencyEnum = {
    Weekly: 'WEEKLY',
    Monthly: 'MONTHLY',
    Yearly: 'YEARLY'
} as const;
export type RecurringFinancialRecordEntityFrequencyEnum = typeof RecurringFinancialRecordEntityFrequencyEnum[keyof typeof RecurringFinancialRecordEntityFrequencyEnum];


/**
 * Check if a given object implements the RecurringFinancialRecordEntity interface.
 */
export function instanceOfRecurringFinancialRecordEntity(value: object): value is RecurringFinancialRecordEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('firstOccurrenceDate' in value) || value['firstOccurrenceDate'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    if (!('repetitionDay' in value) || value['repetitionDay'] === undefined) return false;
    return true;
}

export function RecurringFinancialRecordEntityFromJSON(json: any): RecurringFinancialRecordEntity {
    return RecurringFinancialRecordEntityFromJSONTyped(json, false);
}

export function RecurringFinancialRecordEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringFinancialRecordEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'direction': json['direction'],
        'firstOccurrenceDate': json['firstOccurrenceDate'],
        'description': json['description'],
        'contact': json['contact'],
        'subcategory': json['subcategory'],
        'amount': json['amount'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'files': json['files'] == null ? undefined : json['files'],
        'frequency': json['frequency'],
        'repetitionDay': json['repetitionDay'],
        'repetitionMonth': json['repetitionMonth'] == null ? undefined : json['repetitionMonth'],
        'onlyBusinessDays': json['onlyBusinessDays'] == null ? undefined : json['onlyBusinessDays'],
        'automaticCompletion': json['automaticCompletion'] == null ? undefined : json['automaticCompletion'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'populatedContact': json['populatedContact'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedContactFromJSON(json['populatedContact']),
        'populatedTags': json['populatedTags'] == null ? undefined : ((json['populatedTags'] as Array<any>).map(TagsPageEntityItemsInnerFromJSON)),
        'populatedSubcategory': json['populatedSubcategory'] == null ? undefined : CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryFromJSON(json['populatedSubcategory']),
        'populatedFiles': json['populatedFiles'] == null ? undefined : ((json['populatedFiles'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerFromJSON)),
    };
}

export function RecurringFinancialRecordEntityToJSON(json: any): RecurringFinancialRecordEntity {
    return RecurringFinancialRecordEntityToJSONTyped(json, false);
}

export function RecurringFinancialRecordEntityToJSONTyped(value?: RecurringFinancialRecordEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'direction': value['direction'],
        'firstOccurrenceDate': value['firstOccurrenceDate'],
        'description': value['description'],
        'contact': value['contact'],
        'subcategory': value['subcategory'],
        'amount': value['amount'],
        'tags': value['tags'],
        'files': value['files'],
        'frequency': value['frequency'],
        'repetitionDay': value['repetitionDay'],
        'repetitionMonth': value['repetitionMonth'],
        'onlyBusinessDays': value['onlyBusinessDays'],
        'automaticCompletion': value['automaticCompletion'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'populatedContact': CreateFinancialRecordRequestBodyDtoPopulatedContactToJSON(value['populatedContact']),
        'populatedTags': value['populatedTags'] == null ? undefined : ((value['populatedTags'] as Array<any>).map(TagsPageEntityItemsInnerToJSON)),
        'populatedSubcategory': CreateRecurringFinancialRecordRequestBodyDtoPopulatedSubcategoryToJSON(value['populatedSubcategory']),
        'populatedFiles': value['populatedFiles'] == null ? undefined : ((value['populatedFiles'] as Array<any>).map(CreateFinancialRecordRequestBodyDtoPopulatedFilesInnerToJSON)),
    };
}

