/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshClerkUserRequestBodyDto
 */
export interface RefreshClerkUserRequestBodyDto {
    /**
     * 
     * @type {string}
     * @memberof RefreshClerkUserRequestBodyDto
     */
    token: string;
}

/**
 * Check if a given object implements the RefreshClerkUserRequestBodyDto interface.
 */
export function instanceOfRefreshClerkUserRequestBodyDto(value: object): value is RefreshClerkUserRequestBodyDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function RefreshClerkUserRequestBodyDtoFromJSON(json: any): RefreshClerkUserRequestBodyDto {
    return RefreshClerkUserRequestBodyDtoFromJSONTyped(json, false);
}

export function RefreshClerkUserRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshClerkUserRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function RefreshClerkUserRequestBodyDtoToJSON(json: any): RefreshClerkUserRequestBodyDto {
    return RefreshClerkUserRequestBodyDtoToJSONTyped(json, false);
}

export function RefreshClerkUserRequestBodyDtoToJSONTyped(value?: RefreshClerkUserRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

