/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShouldAiSuggestActionResponseDto
 */
export interface ShouldAiSuggestActionResponseDto {
    /**
     * Indica se a AI deve sugerir uma ação para a transação bancária.
     * @type {boolean}
     * @memberof ShouldAiSuggestActionResponseDto
     */
    shouldAiSuggestAction: boolean;
}

/**
 * Check if a given object implements the ShouldAiSuggestActionResponseDto interface.
 */
export function instanceOfShouldAiSuggestActionResponseDto(value: object): value is ShouldAiSuggestActionResponseDto {
    if (!('shouldAiSuggestAction' in value) || value['shouldAiSuggestAction'] === undefined) return false;
    return true;
}

export function ShouldAiSuggestActionResponseDtoFromJSON(json: any): ShouldAiSuggestActionResponseDto {
    return ShouldAiSuggestActionResponseDtoFromJSONTyped(json, false);
}

export function ShouldAiSuggestActionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShouldAiSuggestActionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'shouldAiSuggestAction': json['shouldAiSuggestAction'],
    };
}

export function ShouldAiSuggestActionResponseDtoToJSON(json: any): ShouldAiSuggestActionResponseDto {
    return ShouldAiSuggestActionResponseDtoToJSONTyped(json, false);
}

export function ShouldAiSuggestActionResponseDtoToJSONTyped(value?: ShouldAiSuggestActionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shouldAiSuggestAction': value['shouldAiSuggestAction'],
    };
}

