/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory';
import type { CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory } from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory';
import {
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSONTyped,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON,
    CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSONTyped,
} from './CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory';

/**
 * 
 * @export
 * @interface SubcategoriesPageEntityItemsInner
 */
export interface SubcategoriesPageEntityItemsInner {
    /**
     * Identificador da subcategoria.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    id: string;
    /**
     * Identificador da organização dona da subcategoria.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    ownerOrganization: string;
    /**
     * Nome da subcategoria.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    name: string;
    /**
     * Slug da subcategoria.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    slug: string;
    /**
     * Índice da subcategoria.
     * @type {number}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    index: number;
    /**
     * Identificador da categoria.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    category: string;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    populatedCategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategory | null;
    /**
     * Identificador da subcategoria normalizada.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    normalizedSubcategory?: string | null;
    /**
     * 
     * @type {CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    populatedNormalizedSubcategory?: CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategory | null;
    /**
     * Indica se a subcategoria deve ser exibida no DRE.
     * @type {boolean}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    considerInDre: boolean;
    /**
     * Descrição da subcategoria.
     * @type {string}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    description: string;
    /**
     * Indica se a subcategoria está ativa.
     * @type {boolean}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    active?: boolean;
    /**
     * Pontuação de busca da subcategoria.
     * @type {number}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    searchScore?: number | null;
    /**
     * Data de criação da subcategoria.
     * @type {any}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    createdAt: any | null;
    /**
     * Data de atualização da subcategoria.
     * @type {any}
     * @memberof SubcategoriesPageEntityItemsInner
     */
    updatedAt: any | null;
}

/**
 * Check if a given object implements the SubcategoriesPageEntityItemsInner interface.
 */
export function instanceOfSubcategoriesPageEntityItemsInner(value: object): value is SubcategoriesPageEntityItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerOrganization' in value) || value['ownerOrganization'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('considerInDre' in value) || value['considerInDre'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SubcategoriesPageEntityItemsInnerFromJSON(json: any): SubcategoriesPageEntityItemsInner {
    return SubcategoriesPageEntityItemsInnerFromJSONTyped(json, false);
}

export function SubcategoriesPageEntityItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubcategoriesPageEntityItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerOrganization': json['ownerOrganization'],
        'name': json['name'],
        'slug': json['slug'],
        'index': json['index'],
        'category': json['category'],
        'populatedCategory': json['populatedCategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryFromJSON(json['populatedCategory']),
        'normalizedSubcategory': json['normalizedSubcategory'] == null ? undefined : json['normalizedSubcategory'],
        'populatedNormalizedSubcategory': json['populatedNormalizedSubcategory'] == null ? undefined : CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryFromJSON(json['populatedNormalizedSubcategory']),
        'considerInDre': json['considerInDre'],
        'description': json['description'],
        'active': json['active'] == null ? undefined : json['active'],
        'searchScore': json['searchScore'] == null ? undefined : json['searchScore'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function SubcategoriesPageEntityItemsInnerToJSON(json: any): SubcategoriesPageEntityItemsInner {
    return SubcategoriesPageEntityItemsInnerToJSONTyped(json, false);
}

export function SubcategoriesPageEntityItemsInnerToJSONTyped(value?: SubcategoriesPageEntityItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerOrganization': value['ownerOrganization'],
        'name': value['name'],
        'slug': value['slug'],
        'index': value['index'],
        'category': value['category'],
        'populatedCategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedCategoryToJSON(value['populatedCategory']),
        'normalizedSubcategory': value['normalizedSubcategory'],
        'populatedNormalizedSubcategory': CreateFinancialRecordRequestBodyDtoPopulatedSubcategoryPopulatedNormalizedSubcategoryToJSON(value['populatedNormalizedSubcategory']),
        'considerInDre': value['considerInDre'],
        'description': value['description'],
        'active': value['active'],
        'searchScore': value['searchScore'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

