/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner } from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner';
import {
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerFromJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerFromJSONTyped,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerToJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerToJSONTyped,
} from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner';

/**
 * Objeto contendo três listas de contatos ordenadas por diferentes métricas
 * @export
 * @interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts
 */
export interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts {
    /**
     * Top contatos por soma total do search score
     * @type {Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner>}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts
     */
    topByTotalSearchScore: Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner>;
    /**
     * Top contatos por média do search score
     * @type {Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner>}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts
     */
    topByMeanSearchScore: Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner>;
    /**
     * Top contatos por frequência relativa
     * @type {Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner>}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts
     */
    topByRelativeFrequency: Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInner>;
}

/**
 * Check if a given object implements the SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts interface.
 */
export function instanceOfSystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts(value: object): value is SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts {
    if (!('topByTotalSearchScore' in value) || value['topByTotalSearchScore'] === undefined) return false;
    if (!('topByMeanSearchScore' in value) || value['topByMeanSearchScore'] === undefined) return false;
    if (!('topByRelativeFrequency' in value) || value['topByRelativeFrequency'] === undefined) return false;
    return true;
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsFromJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsFromJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts {
    if (json == null) {
        return json;
    }
    return {
        
        'topByTotalSearchScore': ((json['topByTotalSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerFromJSON)),
        'topByMeanSearchScore': ((json['topByMeanSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerFromJSON)),
        'topByRelativeFrequency': ((json['topByRelativeFrequency'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerFromJSON)),
    };
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsToJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsToJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsToJSONTyped(value?: SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topByTotalSearchScore': ((value['topByTotalSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerToJSON)),
        'topByMeanSearchScore': ((value['topByMeanSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerToJSON)),
        'topByRelativeFrequency': ((value['topByRelativeFrequency'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsTopByTotalSearchScoreInnerToJSON)),
    };
}

