/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories } from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories';
import {
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesFromJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesFromJSONTyped,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesToJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesToJSONTyped,
} from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories';

/**
 * 
 * @export
 * @interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
 */
export interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    /**
     * 
     * @type {SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    subcategories: SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories;
    /**
     * Soma total dos scores de todos os lançamentos encontrados
     * @type {number}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    allFinancialRecordsTotalSearchScore: number;
    /**
     * Número de lançamentos similares considerados
     * @type {number}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    nSimilarFinancialRecordsConsidered: number;
    /**
     * Número total de lançamentos financeiros da organização
     * @type {number}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    nTotalFinancialRecords: number;
}

/**
 * Check if a given object implements the SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto interface.
 */
export function instanceOfSystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto(value: object): value is SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    if (!('subcategories' in value) || value['subcategories'] === undefined) return false;
    if (!('allFinancialRecordsTotalSearchScore' in value) || value['allFinancialRecordsTotalSearchScore'] === undefined) return false;
    if (!('nSimilarFinancialRecordsConsidered' in value) || value['nSimilarFinancialRecordsConsidered'] === undefined) return false;
    if (!('nTotalFinancialRecords' in value) || value['nTotalFinancialRecords'] === undefined) return false;
    return true;
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoFromJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoFromJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subcategories': SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesFromJSON(json['subcategories']),
        'allFinancialRecordsTotalSearchScore': json['allFinancialRecordsTotalSearchScore'],
        'nSimilarFinancialRecordsConsidered': json['nSimilarFinancialRecordsConsidered'],
        'nTotalFinancialRecords': json['nTotalFinancialRecords'],
    };
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoToJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoToJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoToJSONTyped(value?: SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subcategories': SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesToJSON(value['subcategories']),
        'allFinancialRecordsTotalSearchScore': value['allFinancialRecordsTotalSearchScore'],
        'nSimilarFinancialRecordsConsidered': value['nSimilarFinancialRecordsConsidered'],
        'nTotalFinancialRecords': value['nTotalFinancialRecords'],
    };
}

