/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner } from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner';
import {
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerFromJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerFromJSONTyped,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerToJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerToJSONTyped,
} from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner';

/**
 * Objeto contendo três listas de subcategorias ordenadas por diferentes métricas
 * @export
 * @interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories
 */
export interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories {
    /**
     * Top subcategorias por soma total do search score
     * @type {Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner>}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories
     */
    topByTotalSearchScore: Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner>;
    /**
     * Top subcategorias por média do search score
     * @type {Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner>}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories
     */
    topByMeanSearchScore: Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner>;
    /**
     * Top subcategorias por frequência relativa
     * @type {Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner>}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories
     */
    topByRelativeFrequency: Array<SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInner>;
}

/**
 * Check if a given object implements the SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories interface.
 */
export function instanceOfSystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories(value: object): value is SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories {
    if (!('topByTotalSearchScore' in value) || value['topByTotalSearchScore'] === undefined) return false;
    if (!('topByMeanSearchScore' in value) || value['topByMeanSearchScore'] === undefined) return false;
    if (!('topByRelativeFrequency' in value) || value['topByRelativeFrequency'] === undefined) return false;
    return true;
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesFromJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesFromJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories {
    if (json == null) {
        return json;
    }
    return {
        
        'topByTotalSearchScore': ((json['topByTotalSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerFromJSON)),
        'topByMeanSearchScore': ((json['topByMeanSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerFromJSON)),
        'topByRelativeFrequency': ((json['topByRelativeFrequency'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerFromJSON)),
    };
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesToJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesToJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesToJSONTyped(value?: SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategories | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topByTotalSearchScore': ((value['topByTotalSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerToJSON)),
        'topByMeanSearchScore': ((value['topByMeanSearchScore'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerToJSON)),
        'topByRelativeFrequency': ((value['topByRelativeFrequency'] as Array<any>).map(SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoSubcategoriesTopByTotalSearchScoreInnerToJSON)),
    };
}

