/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 1.12.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts } from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts';
import {
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsFromJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsFromJSONTyped,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsToJSON,
    SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsToJSONTyped,
} from './SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts';

/**
 * 
 * @export
 * @interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
 */
export interface SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    /**
     * 
     * @type {SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    contacts: SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContacts;
    /**
     * Soma total dos scores de todos os lançamentos encontrados
     * @type {number}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    allFinancialRecordsTotalSearchScore: number;
    /**
     * Número de lançamentos encontrados (até 256)
     * @type {number}
     * @memberof SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto
     */
    nFinancialRecordsFound: number;
}

/**
 * Check if a given object implements the SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto interface.
 */
export function instanceOfSystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto(value: object): value is SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    if (!('allFinancialRecordsTotalSearchScore' in value) || value['allFinancialRecordsTotalSearchScore'] === undefined) return false;
    if (!('nFinancialRecordsFound' in value) || value['nFinancialRecordsFound'] === undefined) return false;
    return true;
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoFromJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoFromJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'contacts': SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsFromJSON(json['contacts']),
        'allFinancialRecordsTotalSearchScore': json['allFinancialRecordsTotalSearchScore'],
        'nFinancialRecordsFound': json['nFinancialRecordsFound'],
    };
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoToJSON(json: any): SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto {
    return SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoToJSONTyped(json, false);
}

export function SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoToJSONTyped(value?: SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contacts': SystemGenerateMostCommonContactsForSimilarFinancialRecordReportResponseDtoContactsToJSON(value['contacts']),
        'allFinancialRecordsTotalSearchScore': value['allFinancialRecordsTotalSearchScore'],
        'nFinancialRecordsFound': value['nFinancialRecordsFound'],
    };
}

