/* tslint:disable */
/* eslint-disable */
/**
 * Sofia core-api
 * Api principal do sistema da Sofia para gerenciamento financeiro de startups e empresas modernas.
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactsPageDtoPageInfo } from './ContactsPageDtoPageInfo';
import {
    ContactsPageDtoPageInfoFromJSON,
    ContactsPageDtoPageInfoFromJSONTyped,
    ContactsPageDtoPageInfoToJSON,
    ContactsPageDtoPageInfoToJSONTyped,
} from './ContactsPageDtoPageInfo';
import type { SystemFinancialRecordsPageDtoAggregatedResultReport } from './SystemFinancialRecordsPageDtoAggregatedResultReport';
import {
    SystemFinancialRecordsPageDtoAggregatedResultReportFromJSON,
    SystemFinancialRecordsPageDtoAggregatedResultReportFromJSONTyped,
    SystemFinancialRecordsPageDtoAggregatedResultReportToJSON,
    SystemFinancialRecordsPageDtoAggregatedResultReportToJSONTyped,
} from './SystemFinancialRecordsPageDtoAggregatedResultReport';
import type { SystemFinancialRecordsPageDtoExportedPdfListFile } from './SystemFinancialRecordsPageDtoExportedPdfListFile';
import {
    SystemFinancialRecordsPageDtoExportedPdfListFileFromJSON,
    SystemFinancialRecordsPageDtoExportedPdfListFileFromJSONTyped,
    SystemFinancialRecordsPageDtoExportedPdfListFileToJSON,
    SystemFinancialRecordsPageDtoExportedPdfListFileToJSONTyped,
} from './SystemFinancialRecordsPageDtoExportedPdfListFile';
import type { SystemFinancialRecordsPageDtoExportedPdfTableFile } from './SystemFinancialRecordsPageDtoExportedPdfTableFile';
import {
    SystemFinancialRecordsPageDtoExportedPdfTableFileFromJSON,
    SystemFinancialRecordsPageDtoExportedPdfTableFileFromJSONTyped,
    SystemFinancialRecordsPageDtoExportedPdfTableFileToJSON,
    SystemFinancialRecordsPageDtoExportedPdfTableFileToJSONTyped,
} from './SystemFinancialRecordsPageDtoExportedPdfTableFile';
import type { SystemFinancialRecordsPageDtoExportedExcelFile } from './SystemFinancialRecordsPageDtoExportedExcelFile';
import {
    SystemFinancialRecordsPageDtoExportedExcelFileFromJSON,
    SystemFinancialRecordsPageDtoExportedExcelFileFromJSONTyped,
    SystemFinancialRecordsPageDtoExportedExcelFileToJSON,
    SystemFinancialRecordsPageDtoExportedExcelFileToJSONTyped,
} from './SystemFinancialRecordsPageDtoExportedExcelFile';
import type { SystemFinancialRecordsPageDtoItemsInner } from './SystemFinancialRecordsPageDtoItemsInner';
import {
    SystemFinancialRecordsPageDtoItemsInnerFromJSON,
    SystemFinancialRecordsPageDtoItemsInnerFromJSONTyped,
    SystemFinancialRecordsPageDtoItemsInnerToJSON,
    SystemFinancialRecordsPageDtoItemsInnerToJSONTyped,
} from './SystemFinancialRecordsPageDtoItemsInner';

/**
 * 
 * @export
 * @interface SystemFinancialRecordsPageDto
 */
export interface SystemFinancialRecordsPageDto {
    /**
     * 
     * @type {Array<SystemFinancialRecordsPageDtoItemsInner>}
     * @memberof SystemFinancialRecordsPageDto
     */
    items: Array<SystemFinancialRecordsPageDtoItemsInner>;
    /**
     * 
     * @type {ContactsPageDtoPageInfo}
     * @memberof SystemFinancialRecordsPageDto
     */
    pageInfo: ContactsPageDtoPageInfo;
    /**
     * 
     * @type {SystemFinancialRecordsPageDtoExportedExcelFile}
     * @memberof SystemFinancialRecordsPageDto
     */
    exportedExcelFile?: SystemFinancialRecordsPageDtoExportedExcelFile;
    /**
     * 
     * @type {SystemFinancialRecordsPageDtoExportedPdfTableFile}
     * @memberof SystemFinancialRecordsPageDto
     */
    exportedPdfTableFile?: SystemFinancialRecordsPageDtoExportedPdfTableFile;
    /**
     * 
     * @type {SystemFinancialRecordsPageDtoExportedPdfListFile}
     * @memberof SystemFinancialRecordsPageDto
     */
    exportedPdfListFile?: SystemFinancialRecordsPageDtoExportedPdfListFile;
    /**
     * Observações sobre os arquivos exportados.
     * @type {string}
     * @memberof SystemFinancialRecordsPageDto
     */
    exportedFilesObservations?: string;
    /**
     * 
     * @type {SystemFinancialRecordsPageDtoAggregatedResultReport}
     * @memberof SystemFinancialRecordsPageDto
     */
    aggregatedResultReport: SystemFinancialRecordsPageDtoAggregatedResultReport;
}

/**
 * Check if a given object implements the SystemFinancialRecordsPageDto interface.
 */
export function instanceOfSystemFinancialRecordsPageDto(value: object): value is SystemFinancialRecordsPageDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pageInfo' in value) || value['pageInfo'] === undefined) return false;
    if (!('aggregatedResultReport' in value) || value['aggregatedResultReport'] === undefined) return false;
    return true;
}

export function SystemFinancialRecordsPageDtoFromJSON(json: any): SystemFinancialRecordsPageDto {
    return SystemFinancialRecordsPageDtoFromJSONTyped(json, false);
}

export function SystemFinancialRecordsPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemFinancialRecordsPageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SystemFinancialRecordsPageDtoItemsInnerFromJSON)),
        'pageInfo': ContactsPageDtoPageInfoFromJSON(json['pageInfo']),
        'exportedExcelFile': json['exportedExcelFile'] == null ? undefined : SystemFinancialRecordsPageDtoExportedExcelFileFromJSON(json['exportedExcelFile']),
        'exportedPdfTableFile': json['exportedPdfTableFile'] == null ? undefined : SystemFinancialRecordsPageDtoExportedPdfTableFileFromJSON(json['exportedPdfTableFile']),
        'exportedPdfListFile': json['exportedPdfListFile'] == null ? undefined : SystemFinancialRecordsPageDtoExportedPdfListFileFromJSON(json['exportedPdfListFile']),
        'exportedFilesObservations': json['exportedFilesObservations'] == null ? undefined : json['exportedFilesObservations'],
        'aggregatedResultReport': SystemFinancialRecordsPageDtoAggregatedResultReportFromJSON(json['aggregatedResultReport']),
    };
}

export function SystemFinancialRecordsPageDtoToJSON(json: any): SystemFinancialRecordsPageDto {
    return SystemFinancialRecordsPageDtoToJSONTyped(json, false);
}

export function SystemFinancialRecordsPageDtoToJSONTyped(value?: SystemFinancialRecordsPageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SystemFinancialRecordsPageDtoItemsInnerToJSON)),
        'pageInfo': ContactsPageDtoPageInfoToJSON(value['pageInfo']),
        'exportedExcelFile': SystemFinancialRecordsPageDtoExportedExcelFileToJSON(value['exportedExcelFile']),
        'exportedPdfTableFile': SystemFinancialRecordsPageDtoExportedPdfTableFileToJSON(value['exportedPdfTableFile']),
        'exportedPdfListFile': SystemFinancialRecordsPageDtoExportedPdfListFileToJSON(value['exportedPdfListFile']),
        'exportedFilesObservations': value['exportedFilesObservations'],
        'aggregatedResultReport': SystemFinancialRecordsPageDtoAggregatedResultReportToJSON(value['aggregatedResultReport']),
    };
}

