/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus core-api
 * Api principal do sistema Pegasus para gerenciamento financeiro de pequenas e médias empresas.
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrganizationRequestBodyDto
 */
export interface UpdateOrganizationRequestBodyDto {
    /**
     * Subtipo da organização.
     * @type {string}
     * @memberof UpdateOrganizationRequestBodyDto
     */
    subtype?: UpdateOrganizationRequestBodyDtoSubtypeEnum;
}


/**
 * @export
 */
export const UpdateOrganizationRequestBodyDtoSubtypeEnum = {
    IndependentPersonal: 'INDEPENDENT_PERSONAL',
    IndependentBussiness: 'INDEPENDENT_BUSSINESS',
    BpoManagedPersonal: 'BPO_MANAGED_PERSONAL',
    BpoManagedBusiness: 'BPO_MANAGED_BUSINESS',
    BpoOffice: 'BPO_OFFICE'
} as const;
export type UpdateOrganizationRequestBodyDtoSubtypeEnum = typeof UpdateOrganizationRequestBodyDtoSubtypeEnum[keyof typeof UpdateOrganizationRequestBodyDtoSubtypeEnum];


/**
 * Check if a given object implements the UpdateOrganizationRequestBodyDto interface.
 */
export function instanceOfUpdateOrganizationRequestBodyDto(value: object): value is UpdateOrganizationRequestBodyDto {
    return true;
}

export function UpdateOrganizationRequestBodyDtoFromJSON(json: any): UpdateOrganizationRequestBodyDto {
    return UpdateOrganizationRequestBodyDtoFromJSONTyped(json, false);
}

export function UpdateOrganizationRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
    };
}

export function UpdateOrganizationRequestBodyDtoToJSON(json: any): UpdateOrganizationRequestBodyDto {
    return UpdateOrganizationRequestBodyDtoToJSONTyped(json, false);
}

export function UpdateOrganizationRequestBodyDtoToJSONTyped(value?: UpdateOrganizationRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subtype': value['subtype'],
    };
}

